/* =========================================================================
 *  RED CRIME - Oyun yapılandırması
 *  Sabitler, bölüm tanımları, geliştirmeler ve senaryo metinleri.
 * ========================================================================= */
(function (RC) {
  'use strict';

  const Config = {
    VIEW_H: 720, // mantıksal görüş yüksekliği
    MIN_VIEW_W: 960,

    // Dünya ölçüleri
    FLOOR_H: 300, // bir katın yüksekliği (döşemeden döşemeye)
    SLAB: 24, // döşeme kalınlığı
    WALL: 24, // dış duvar kalınlığı
    DOOR_H: 150, // kapı boşluğu yüksekliği
    STEP_H: 20,
    STEP_W: 28,
    GRAVITY: 1900,
    STEP_UP: 22,
    STREET_W: 900,

    // Soygun süresi karmaşıklığa göre ölçeklenir (sn). Bkz. Config.heistTime()
    HEIST_TIMES: [300, 300, 300], // ilk üç bölüm 5 dk
    HEIST_TIME_MAX: 900, // geç dönem kontratlar en fazla 15 dk
    // Dükkânların açılması için bitirilmesi gereken bölüm sayısı
    SHOP_UNLOCK: 2, // Karaborsa: 2. bölümü bitir
    DARKWEB_UNLOCK: 4, // Karanlık Ağ: 4. bölümü bitir
    // Ekonomi dengesi (bölüm hedefine oranla). Tek eşya ya da tek kasa görevi bitirmesin.
    ITEM_VALUE_CAP: 0.12, // bir eşyanın yumuşak tavanı: hedefin %12'si
    SAFE_BUDGET: 0.6, // kasanın toplam içeriği: hedefin ~%60'ı
    SAFE_ITEM_CAP: 0.35, // kasadaki tek parça: kasa bütçesinin en fazla ~%35'i
    FINAL_ATTEMPTS: 2,
    DEVELOPER: 'Red Crime Studio', // geliştirici adı (jenerikte görünür)

    FONT_TITLE: '"Bungee", "Impact", "Arial Black", sans-serif',
    FONT_UI: '"Rubik", "Segoe UI", "Helvetica Neue", Arial, sans-serif',
    FONT_MONO: '"Share Tech Mono", "Courier New", monospace',

    COLORS: {
      red: '#e8283c',
      redDark: '#8f1020',
      gold: '#ffc83d',
      night: '#070914',
      panel: '#12162a',
      panelLight: '#1d2340',
      text: '#f2f4ff',
      textDim: '#9aa3c7',
      green: '#3ddc84',
      blue: '#4aa8ff',
      purple: '#b467ff',
      orange: '#ff8c2e',
    },

    RARITY: [
      { id: 'common', name: 'Sıradan', mult: 1, color: '#d8dcef', chance: 0.72 },
      { id: 'rare', name: 'Nadir', mult: 2.2, color: '#4aa8ff', chance: 0.19 },
      { id: 'epic', name: 'Epik', mult: 4.5, color: '#b467ff', chance: 0.075 },
      { id: 'legendary', name: 'Efsanevi', mult: 11, color: '#ffc83d', chance: 0.015 },
    ],

    DIFFICULTY: {
      easy: { name: 'Kolay', hearing: 0.65, sight: 0.75, speed: 0.85, time: 1.2, decay: 1.4 },
      normal: { name: 'Normal', hearing: 1, sight: 1, speed: 1, time: 1, decay: 1 },
      hard: { name: 'Zor', hearing: 1.4, sight: 1.25, speed: 1.12, time: 0.85, decay: 0.7 },
    },

    /* ------------------------------------------------------------------
     * BÖLÜMLER
     * ---------------------------------------------------------------- */
    LEVELS: [
      {
        id: 1,
        name: 'Emekli Öğretmenin Evi',
        short: 'Küçük İki Katlı Ev',
        desc: 'Mahallenin sessiz köşesinde iki katlı, sevimli bir ev. Emekli Öğretmen üst kattaki yatak odasında, kapısı kapalı uyur.',
        floors: 2,
        basement: false,
        width: 2700,
        garden: 420,
        residents: [{ name: 'Emekli Öğretmen', color: '#6f8fd6', cap: '#e8e0c8', mustache: true, sleepDepth: 1.0, look: { sex: 'm', age: 'old', build: 0.95, hair: 'bald', hairColor: '#d8d2ca', skin: '#e6bf9c', glasses: true, outfit: 'pajama', top: '#6f84b8', bottom: '#58699a', accent: '#e8e0c8' } }],
        dog: false,
        items: 240,
        target: 12000,
        stars: [12000, 24000, 40000],
        seed: 1107,
        facade: '#b9876a',
        roof: '#7a3b2e',
        theme: 'cozy',
        pool: false,
        shed: false,
        truckColor: '#c23a2b',
        weather: 'clear',
        bedroomLocked: false,
        lockedDoors: 0,
        closedDoors: 1,
        security: { cameras: 0, lasers: 0, panel: false, guards: 0, blink: false },
      },
      {
        id: 2,
        name: 'Kasabın Evi',
        short: 'Eski İki Katlı Ev',
        desc: 'Kasap dükkânın hasılatını eve getirir. Yatak odasının kapısını hep kilitler; eski evin merdivenleri ve döşemesi gıcırdar.',
        floors: 2,
        basement: false,
        width: 3200,
        garden: 520,
        residents: [{ name: 'Kasap', color: '#c94f4f', cap: '#f0f0f0', mustache: true, sleepDepth: 0.95, look: { sex: 'm', age: 'adult', build: 1.35, hair: 'buzz', hairColor: '#241a14', skin: '#d9a47e', beard: 'stubble', outfit: 'undershirt', top: '#ecebe6', bottom: '#3a3f4e', accent: '#ffffff' } }],
        dog: false,
        items: 384,
        target: 25000,
        stars: [25000, 50000, 85000],
        seed: 2213,
        facade: '#d8c9a7',
        roof: '#44526b',
        theme: 'classic',
        pool: false,
        shed: false,
        truckColor: '#2b6cc2',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 1,
        closedDoors: 2,
        security: { cameras: 0, lasers: 0, panel: false, guards: 0, blink: false },
      },
      {
        id: 3,
        name: 'Doktorun Dubleksi',
        short: 'Dubleks + Bodrum',
        desc: 'Modern bir dubleks ve gizemli bir bodrum. Doktor kuş uykusu uyur; çalışma odası ve bodrum kilitlidir.',
        floors: 2,
        basement: true,
        width: 2900,
        garden: 640,
        residents: [{ name: 'Doktor', color: '#3fae9a', cap: '#f6c1d8', mustache: false, sleepDepth: 0.85, look: { sex: 'f', age: 'adult', build: 0.9, hair: 'bun', hairColor: '#3a2418', skin: '#ecc6a4', glasses: true, outfit: 'robe', top: '#3f9e8c', bottom: '#e8e0d6', accent: '#f6c1d8' } }],
        dog: false,
        items: 896,
        target: 70000,
        stars: [70000, 140000, 230000],
        seed: 3371,
        facade: '#e6e6e6',
        roof: '#2e2e36',
        theme: 'modern',
        pool: false,
        shed: false,
        truckColor: '#2e9e5b',
        weather: 'fog',
        bedroomLocked: true,
        lockedDoors: 2,
        closedDoors: 2,
        security: { cameras: 0, lasers: 0, panel: false, guards: 0, blink: false },
      },
      {
        id: 4,
        name: 'Kuyumcunun Evi',
        short: 'İki Kat + Bodrum · Kameralar',
        desc: 'Kapalıçarşı\'nın en zengin kuyumcusu. Evinde ilk kez güvenlik kameraları ve bir alarm sistemi var. Kamera seni görürse alarm çalar!',
        floors: 2,
        basement: true,
        width: 3000,
        garden: 600,
        residents: [{ name: 'Kuyumcu', color: '#c9a24a', cap: '#8a1b2a', mustache: true, sleepDepth: 0.9, look: { sex: 'm', age: 'old', build: 1.15, hair: 'bald', hairColor: '#a8a29a', skin: '#dcae88', outfit: 'robe', top: '#7a1f2c', bottom: '#d9c9a8', accent: '#c9a24a' } }],
        dog: false,
        items: 960,
        target: 90000,
        stars: [90000, 170000, 280000],
        seed: 4421,
        facade: '#c8b8a0',
        roof: '#3a2a22',
        theme: 'classic',
        pool: false,
        shed: false,
        truckColor: '#b8861a',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 2,
        closedDoors: 2,
        security: { cameras: 3, lasers: 0, panel: true, guards: 0, blink: false },
      },
      {
        id: 5,
        name: 'Holding Patronunun Rezidansı',
        short: 'Dört Katlı Rezidans',
        desc: 'Dört kat, iki sakin, kameralar ve ilk lazer alarmı. Holding Patronu ve eşi ayrı katlarda, kilitli odalarda uyur.',
        floors: 4,
        basement: false,
        width: 3200,
        garden: 560,
        residents: [
          { name: 'Holding Patronu', color: '#39406b', cap: '#ffd76a', mustache: true, sleepDepth: 0.9, look: { sex: 'm', age: 'adult', build: 1.1, hair: 'slick', hairColor: '#1c1a1a', skin: '#e2b48e', outfit: 'pajama', top: '#2c3560', bottom: '#222a4c', accent: '#ffd76a' } },
          { name: 'Patronun Eşi', color: '#a54fa0', cap: '#ffe3f2', mustache: false, sleepDepth: 0.85, look: { sex: 'f', age: 'adult', build: 0.88, hair: 'long', hairColor: '#5a3220', skin: '#efc9a8', outfit: 'robe', top: '#8e3f8a', bottom: '#f0dbe8', accent: '#ffe3f2' } },
        ],
        dog: false,
        items: 1040,
        target: 120000,
        stars: [120000, 220000, 360000],
        seed: 4409,
        facade: '#9a8f86',
        roof: '#23262f',
        theme: 'luxury',
        pool: false,
        shed: false,
        truckColor: '#6b3cc2',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 3,
        closedDoors: 3,
        security: { cameras: 4, lasers: 2, panel: true, guards: 0, blink: false },
      },
      {
        id: 6,
        name: 'Koleksiyoncunun Galeri Villası',
        short: 'Üç Katlı Sanat Villası',
        desc: 'Ünlü bir sanat koleksiyoncusunun villası bir müze gibi: duvarlarda başyapıtlar, koridorlarda lazerler, köşelerde kameralar.',
        floors: 3,
        basement: false,
        width: 3300,
        garden: 900,
        residents: [{ name: 'Koleksiyoncu', color: '#7a3a6a', cap: '#f0e0ff', mustache: false, sleepDepth: 0.85, look: { sex: 'f', age: 'old', build: 0.9, hair: 'bob', hairColor: '#cfd0d6', skin: '#ebc6a6', glasses: true, outfit: 'robe', top: '#5c2f58', bottom: '#2a1a28', accent: '#f0e0ff' } }],
        dog: false,
        items: 1280,
        target: 180000,
        stars: [180000, 330000, 520000],
        seed: 6613,
        facade: '#f2efe8',
        roof: '#34384a',
        theme: 'gallery',
        pool: false,
        shed: false,
        truckColor: '#e8e8ec',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 4,
        closedDoors: 3,
        security: { cameras: 6, lasers: 5, panel: true, guards: 0, blink: true },
      },
      {
        id: 7,
        name: 'Yıldız Futbolcunun Malikânesi',
        short: 'Havuzlu Malikâne + Köpek',
        desc: 'Süper Lig\'in yıldız golcüsünün malikânesi. Havuz, oyun odası, kupa dolapları... ve bahçede bir bekçi köpeği.',
        floors: 3,
        basement: true,
        width: 3400,
        garden: 1800,
        residents: [{ name: 'Golcü', color: '#2a8a4a', cap: '#ffffff', mustache: false, sleepDepth: 0.8, look: { sex: 'm', age: 'young', build: 1.05, hair: 'buzz', hairColor: '#1a1410', skin: '#b98260', beard: 'stubble', outfit: 'tracksuit', top: '#1f7a3e', bottom: '#1a4f2c', accent: '#ffffff' } }],
        dog: true,
        items: 1600,
        target: 240000,
        stars: [240000, 440000, 700000],
        seed: 7717,
        facade: '#e0dcd4',
        roof: '#2a3a4a',
        theme: 'sport',
        pool: true,
        shed: false,
        truckColor: '#1f7a4a',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 4,
        closedDoors: 4,
        security: { cameras: 7, lasers: 5, panel: true, guards: 0, blink: true, motion: 1, plates: 0, sweepers: 0 },
      },
      {
        id: 8,
        name: 'Milletvekilinin Boğaz Yalısı',
        short: 'Yalı + Özel Güvenlik',
        desc: 'Boğaz kıyısında tarihi bir yalı. Artık bir özel güvenlik görevlisi de var: uyumaz, el feneriyle devriye gezer.',
        floors: 3,
        basement: true,
        width: 3600,
        garden: 1300,
        residents: [
          { name: 'Milletvekili', color: '#5a4a3a', cap: '#e8e0c8', mustache: true, sleepDepth: 0.85, look: { sex: 'm', age: 'old', build: 1.2, hair: 'gray', hairColor: '#bdb7b0', skin: '#e0b08a', outfit: 'robe', top: '#5a4632', bottom: '#e8e0c8', accent: '#e8e0c8' } },
          { name: 'Vekilin Eşi', color: '#8a5a7a', cap: '#ffe0f0', mustache: false, sleepDepth: 0.85, look: { sex: 'f', age: 'adult', build: 0.95, hair: 'bun', hairColor: '#4a2e20', skin: '#edc7a6', outfit: 'robe', top: '#9a5c80', bottom: '#f4e2ec', accent: '#ffe0f0' } },
        ],
        dog: false,
        items: 1840,
        target: 320000,
        stars: [320000, 580000, 900000],
        seed: 8819,
        facade: '#e8dcc0',
        roof: '#5a2a22',
        theme: 'waterfront',
        pool: false,
        shed: true,
        truckColor: '#2a4d8f',
        weather: 'fog',
        bedroomLocked: true,
        lockedDoors: 5,
        closedDoors: 4,
        security: { cameras: 8, lasers: 6, panel: true, guards: 1, blink: true, motion: 2, plates: 0, sweepers: 0 },
      },
      {
        id: 9,
        name: 'Oligarkın Köşkü',
        short: 'Beş Katlı Kale',
        desc: 'Yurt dışından gelen gizemli bir milyarderin köşkü. İki güvenlik görevlisi, yanıp sönen lazerler ve her köşede kamera. Hata affetmez.',
        floors: 4,
        basement: true,
        width: 3500,
        garden: 900,
        residents: [
          { name: 'Oligark', color: '#3a3a4a', cap: '#c0c4cc', mustache: true, sleepDepth: 0.8, look: { sex: 'm', age: 'adult', build: 1.25, hair: 'bald', hairColor: '#8a7f76', skin: '#e8c0a0', beard: 'stubble', outfit: 'robe', top: '#23242c', bottom: '#8a8f9c', accent: '#c0c4cc' } },
          { name: 'Oligarkın Eşi', color: '#8a2a4a', cap: '#ffe8f0', mustache: false, sleepDepth: 0.8, look: { sex: 'f', age: 'adult', build: 0.85, hair: 'long', hairColor: '#e2c27a', skin: '#f2d2b6', outfit: 'robe', top: '#8a1f3c', bottom: '#f6e2e8', accent: '#ffe8f0' } },
        ],
        dog: false,
        items: 2080,
        target: 420000,
        stars: [420000, 760000, 1150000],
        seed: 9923,
        facade: '#6a6a74',
        roof: '#1a1a22',
        theme: 'oligarch',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 7,
        closedDoors: 4,
        security: { cameras: 11, lasers: 9, panel: true, guards: 2, blink: true, motion: 3, plates: 2, sweepers: 0 },
      },
      {
        id: 10,
        name: 'Paşa Konağı',
        short: 'Dev Bahçeli Konak · Final',
        desc: 'Devasa bir bahçe, havuz, kulübe, bir bekçi köpeği, iki bekçi, hazine odası ve şehrin en gelişmiş güvenlik sistemi. Büyük final!',
        floors: 3,
        basement: true,
        width: 4800,
        garden: 3200,
        residents: [
          { name: 'Emekli Paşa', color: '#8a2d2d', cap: '#ffffff', mustache: true, sleepDepth: 0.85, look: { sex: 'm', age: 'old', build: 1.1, hair: 'gray', hairColor: '#e6e2dc', skin: '#dcaa84', outfit: 'robe', top: '#6e2222', bottom: '#e8e0c8', accent: '#ffffff' } },
          { name: 'Paşanın Eşi', color: '#2d6a8a', cap: '#ffd1e0', mustache: false, sleepDepth: 0.8, look: { sex: 'f', age: 'old', build: 0.95, hair: 'bun', hairColor: '#b8b4b0', skin: '#ecc8aa', glasses: true, outfit: 'robe', top: '#2d5a7a', bottom: '#e4ecf2', accent: '#ffd1e0' } },
        ],
        dog: true,
        items: 2720,
        target: 550000,
        stars: [550000, 1000000, 1600000],
        seed: 5557,
        facade: '#efe4cf',
        roof: '#5b2a22',
        theme: 'mansion',
        pool: true,
        shed: true,
        truckColor: '#1f1f24',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 8,
        closedDoors: 5,
        security: { cameras: 13, lasers: 10, panel: true, guards: 2, blink: true, motion: 3, plates: 3, sweepers: 1 },
      },
      {
        id: 11,
        name: 'Altın Sarayı Kuyumcusu',
        short: 'Kuyumcu Soygunu',
        desc: 'Şehrin en büyük kuyumcusu. Vitrinler mücevher dolu, bodrumda kiralık kasalar. Hareket sensörleri ve basınç plakaları ilk kez karşında. Gece bekçisi güvenlik odasında uyukluyor.',
        kind: 'shop',
        sign: 'ALTIN SARAYI',
        floors: 2,
        basement: true,
        width: 2600,
        garden: 320,
        urban: true,
        roomPlan: { '-1': ['vault', 'storage'], 0: ['showroom', 'showroom', 'office'], 1: ['workshop', 'security', 'office'] },
        residents: [{ name: 'Gece Bekçisi', color: '#2a3a6a', cap: '#1b2a55', hat: 'police', mustache: true, sleepDepth: 0.85, bedType: 'cot', look: { sex: 'm', age: 'adult', build: 1.1, hair: 'short', hairColor: '#2a2018', skin: '#d6a47e', outfit: 'uniform', top: '#23304f', bottom: '#161d33', cap: true } }],
        dog: false,
        items: 1120,
        target: 650000,
        stars: [650000, 1100000, 1700000],
        seed: 11011,
        facade: '#3a2a22',
        roof: '#1a1a1e',
        theme: 'luxury',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 3,
        closedDoors: 1,
        security: { cameras: 8, lasers: 4, panel: true, guards: 0, blink: true, motion: 3, plates: 2, sweepers: 0 },
      },
      {
        id: 12,
        name: 'Şehir Tarih Müzesi',
        short: 'Müze Gecesi',
        desc: 'Üç katlı tarih müzesi: dinozor iskeletleri, altın maskeler, kraliyet tacı. Galerileri tarayan lazerler, basınç plakaları ve devriye gezen bir bekçi.',
        kind: 'museum',
        sign: 'TARİH MÜZESİ',
        floors: 3,
        basement: false,
        width: 3600,
        garden: 700,
        urban: true,
        roomPlan: { 0: ['lobby', 'exhibit', 'exhibit', 'exhibit', 'office'], 1: ['exhibit', 'gallery', 'exhibit', 'security'], 2: ['treasure', 'exhibit', 'gallery', 'office'] },
        residents: [{ name: 'Gece Bekçisi', color: '#3a4a3a', cap: '#1b2a55', hat: 'police', mustache: false, sleepDepth: 0.8, bedType: 'cot', look: { sex: 'f', age: 'adult', build: 0.95, hair: 'bun', hairColor: '#2a1a14', skin: '#e2b48e', outfit: 'uniform', top: '#23304f', bottom: '#161d33', cap: true } }],
        dog: false,
        items: 1280,
        target: 800000,
        stars: [800000, 1400000, 2200000],
        seed: 12121,
        facade: '#d8d0c0',
        roof: '#3a3f4a',
        theme: 'gallery',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'fog',
        bedroomLocked: true,
        lockedDoors: 4,
        closedDoors: 2,
        security: { cameras: 10, lasers: 5, panel: true, guards: 1, blink: true, motion: 3, plates: 4, sweepers: 3 },
      },
      {
        id: 13,
        name: 'TeknoPark Mağazası',
        short: 'Dükkân Soygunu',
        desc: 'Şehrin en büyük elektronik mağazası: telefonlar, dizüstüler, konsollar. Deposu bodrumda, müdürün kasası üst katta. İki bekçi ve her rafta kamera.',
        kind: 'shop',
        sign: 'TEKNOPARK',
        floors: 2,
        basement: true,
        width: 3200,
        garden: 360,
        urban: true,
        roomPlan: { '-1': ['storage', 'storage', 'workshop'], 0: ['techshow', 'techshow', 'techshow', 'cashier'], 1: ['techshow', 'office', 'security', 'office'] },
        residents: [{ name: 'Gece Bekçisi', color: '#4a2a2a', cap: '#1b2a55', hat: 'police', mustache: true, sleepDepth: 0.8, bedType: 'cot', look: { sex: 'm', age: 'adult', build: 1.1, hair: 'short', hairColor: '#2a2018', skin: '#d6a47e', outfit: 'uniform', top: '#23304f', bottom: '#161d33', cap: true } }],
        dog: false,
        items: 1360,
        target: 900000,
        stars: [900000, 1500000, 2400000],
        seed: 13131,
        facade: '#2a3a5a',
        roof: '#15151a',
        theme: 'modern',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 4,
        closedDoors: 2,
        security: { cameras: 11, lasers: 5, panel: true, guards: 2, blink: true, motion: 4, plates: 3, sweepers: 1 },
      },
      {
        id: 14,
        name: 'Anadolu Bankası Şubesi',
        short: 'Banka Soygunu · Planlı',
        desc: 'İlk banka işi. Ekibini topla, planı sen yap: giriş noktası, hacker, gözcü, şoför, dikkat dağıtıcı. Kiralık kasalar ve dev kasa bodrumda.',
        kind: 'bank',
        sign: 'ANADOLU BANKASI',
        floors: 2,
        basement: true,
        width: 3400,
        garden: 420,
        urban: true,
        planning: true,
        roomPlan: { '-1': ['vault', 'vault', 'storage'], 0: ['lobby', 'cashier', 'office', 'office'], 1: ['office', 'security', 'office', 'office'] },
        residents: [{ name: 'Gece Bekçisi', color: '#2a3a6a', cap: '#1b2a55', hat: 'police', mustache: true, sleepDepth: 0.75, bedType: 'cot', look: { sex: 'm', age: 'adult', build: 1.1, hair: 'short', hairColor: '#2a2018', skin: '#d6a47e', outfit: 'uniform', top: '#23304f', bottom: '#161d33', cap: true } }],
        dog: false,
        items: 1360,
        target: 1300000,
        stars: [1300000, 2200000, 3500000],
        seed: 14141,
        facade: '#c8c0b0',
        roof: '#2a2a30',
        theme: 'oligarch',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 5,
        closedDoors: 2,
        security: { cameras: 13, lasers: 7, panel: true, guards: 2, blink: true, motion: 5, plates: 5, sweepers: 2 },
      },
      {
        id: 15,
        name: 'Hazine Bankası Genel Müdürlüğü',
        short: 'BÜYÜK VURGUN · 2 Hak',
        desc: 'Her şeyin sonu. Şehrin kalbindeki bankanın genel müdürlüğü. Üç bekçi, onlarca kamera, tarayan lazerler ve dev bir kasa. Sadece iki hakkın var.',
        kind: 'bank',
        sign: 'HAZİNE BANKASI',
        floors: 3,
        basement: true,
        width: 4600,
        garden: 600,
        urban: true,
        planning: true,
        final: true,
        roomPlan: { '-1': ['vault', 'vault', 'vault', 'storage'], 0: ['lobby', 'cashier', 'cashier', 'office', 'lobby'], 1: ['office', 'security', 'office', 'office', 'office'], 2: ['treasure', 'office', 'security', 'office'] },
        residents: [
          { name: 'Kıdemli Bekçi', color: '#2a3a6a', cap: '#1b2a55', hat: 'police', mustache: true, sleepDepth: 0.7, bedType: 'cot', look: { sex: 'm', age: 'old', build: 1.2, hair: 'gray', hairColor: '#bdb7b0', skin: '#dcaa84', outfit: 'uniform', top: '#23304f', bottom: '#161d33', cap: true } },
          { name: 'Gece Bekçisi', color: '#5a2a4a', cap: '#1b2a55', hat: 'police', mustache: false, sleepDepth: 0.7, bedType: 'cot', look: { sex: 'f', age: 'adult', build: 0.95, hair: 'bun', hairColor: '#2a1a14', skin: '#e2b48e', outfit: 'uniform', top: '#23304f', bottom: '#161d33', cap: true } },
        ],
        dog: false,
        items: 1920,
        target: 2500000,
        stars: [2500000, 4000000, 6000000],
        seed: 15151,
        facade: '#b8b0a0',
        roof: '#1a1a1e',
        theme: 'oligarch',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 7,
        closedDoors: 3,
        security: { cameras: 16, lasers: 9, panel: true, guards: 3, blink: true, motion: 6, plates: 6, sweepers: 4 },
      },
    ],

    /* ------------------------------------------------------------------
     * KARANLIK AĞ ÜRÜNLERİ (pahalı, özel ekipman)
     * perm: kalıcı ekipman · diğerleri: tüketilebilir (key: kısayol tuşu)
     * ---------------------------------------------------------------- */
    DARKWEB: [
      { id: 'lockpick', key: '1', name: 'Elektronik Maymuncuk', desc: 'Kilitli bir kapıyı saniyeler içinde, sessizce açar.', price: 95000, pack: 3, icon: 'key' },
      { id: 'jammer', key: '2', name: 'Kamera Karıştırıcı', desc: 'Evdeki tüm kameraları 25 saniye boyunca kör eder.', price: 160000, pack: 2, icon: 'eye' },
      { id: 'sleepgas', key: '3', name: 'Uyku Gazı Bombası', desc: 'Yakınındaki uyanık herkesi (köpek dahil) 25 saniye uyutur.', price: 240000, pack: 2, icon: 'zzz' },
      { id: 'smoke', key: '4', name: 'Sis Bombası', desc: 'Kalın bir duman bulutu: içindeyken kimse seni göremez.', price: 120000, pack: 2, icon: 'cloud' },
      { id: 'pistol', key: '6', name: 'Tabanca', desc: 'Çok pahalı. Havaya uyarı atışı: yakındaki herkes korkup kaçar, ama silah sesi 911\'i anında aratır.', price: 2500000, pack: 3, icon: 'gun' },
      { id: 'emp', key: '5', name: 'EMP Cihazı', desc: 'Alarm sistemini, kameraları ve lazerleri tamamen devre dışı bırakır.', price: 380000, pack: 1, icon: 'bolt' },
      { id: 'nightvision', perm: true, name: 'Gece Görüş Gözlüğü', desc: 'Kalıcı. El feneri olmadan da karanlıkta çok daha geniş görürsün.', price: 480000, icon: 'eye' },
      { id: 'thermal', perm: true, name: 'Termal Tarayıcı', desc: 'Kalıcı. Duvarların ardındaki herkesi ve kasa anahtarını haritada gösterir.', price: 650000, icon: 'map' },
      { id: 'bribe', perm: true, name: 'Şoföre Rüşvet', desc: 'Kalıcı. Şoför her soygunda 45 saniye fazla bekler.', price: 420000, icon: 'truck' },
    ],

    /* ------------------------------------------------------------------
     * REKLAM VE MAĞAZA (yalnızca Android / iOS uygulamasında)
     * Ürün kimlikleri Play Console ve App Store Connect'te AYNEN açılmalı.
     * price: mağaza fiyatı gelmezse gösterilecek yedek etiket.
     * ---------------------------------------------------------------- */
    MONETIZATION: {
      // AdMob reklam birimleri. Şu an Google'ın TEST kimlikleri: gerçek
      // kimlikleri girmeden mağazaya YÜKLEME (test reklamı gelir, gelir gelmez).
      // Uygulama kimliği ayrıca AndroidManifest.xml ve ios/App/App/Info.plist içinde.
      admob: {
        android: {
          banner: 'ca-app-pub-3940256099942544/9214589741',
          interstitial: 'ca-app-pub-3940256099942544/1033173712',
          rewarded: 'ca-app-pub-3940256099942544/5224354917',
        },
        ios: {
          banner: 'ca-app-pub-3940256099942544/2435281174',
          interstitial: 'ca-app-pub-3940256099942544/4411468910',
          rewarded: 'ca-app-pub-3940256099942544/1712485313',
        },
        testing: true, // gerçek kimlikleri girince false yap
      },
      INTERSTITIAL_EVERY: 3, // her 3 soygunda bir tam ekran reklam
      BANNER_SCENES: ['menu', 'levelselect', 'shop', 'darkweb', 'settings', 'howto', 'store'],
      CASH_PACKS: [
        { id: 'redcrime_cash_500k', money: 500000, price: '5 TL' },
        { id: 'redcrime_cash_1m', money: 1000000, price: '10 TL' },
        { id: 'redcrime_cash_2m', money: 2000000, price: '20 TL' },
      ],
      PREMIUM: { id: 'redcrime_premium', price: '49,99 TL' },
      PREMIUM_TIME: 60, // her soygunda +60 sn
      PREMIUM_BAG: 10, // +10 çuval yuvası
      DAILY_BONUS: 50000, // premium günlük para ödülü
    },

    /* ------------------------------------------------------------------
     * GELİŞTİRMELER (Dükkân)
     * ---------------------------------------------------------------- */
    UPGRADES: [
      {
        id: 'shoes',
        name: 'Kedi Pati Ayakkabı',
        desc: 'Ayak seslerini azaltır.',
        icon: 'shoe',
        costs: [12000, 36000, 90000],
        effect: (l) => RC.L('-%{v} ayak sesi', { v: l * 18 }),
      },
      {
        id: 'flashlight',
        name: 'Taktik El Feneri',
        desc: 'Daha uzun ve geniş ışık huzmesi.',
        icon: 'flashlight',
        costs: [9000, 27000, 66000],
        effect: (l) => RC.L('+%{v} menzil', { v: l * 20 }),
      },
      {
        id: 'bag',
        name: 'Büyük Çuval',
        desc: 'Cebe atılabilen küçük eşya kapasitesi.',
        icon: 'bag',
        costs: [15000, 45000, 120000],
        effect: (l) => RC.L('{v} küçük eşya', { v: 14 + l * 6 }),
      },
      {
        id: 'strength',
        name: 'Protein Tozu',
        desc: 'Ağır eşyalar seni daha az yavaşlatır.',
        icon: 'muscle',
        costs: [18000, 54000, 135000],
        effect: (l) => RC.L('-%{v} ağırlık cezası', { v: l * 15 }),
      },
      {
        id: 'safecracker',
        name: 'Kasa Ustası Kursu',
        desc: 'Kasa açma mini oyununda daha geniş hedef.',
        icon: 'safe',
        costs: [24000, 75000],
        effect: (l) => RC.L('+%{v} hedef bölge', { v: l * 35 }),
      },
      {
        id: 'lungs',
        name: 'Maraton Ciğeri',
        desc: 'Koşarken daha hızlısın.',
        icon: 'run',
        costs: [15000, 48000],
        effect: (l) => RC.L('+%{v} koşu hızı', { v: l * 8 }),
      },
    ],

    /* ------------------------------------------------------------------
     * ODA TİPLERİ
     * ---------------------------------------------------------------- */
    ROOM_TYPES: {
      living: { name: 'Salon', wall: ['#5d4a6e', '#4f5f7a', '#6e5a48', '#4d6b5b'], pattern: 'damask' },
      kitchen: { name: 'Mutfak', wall: ['#d9d2b8', '#c7dbd6', '#e0cfc0'], pattern: 'tiles' },
      dining: { name: 'Yemek Odası', wall: ['#7a4b43', '#5b6a4b', '#6a5577'], pattern: 'stripes' },
      bedroom: { name: 'Yatak Odası', wall: ['#4a5a82', '#6b4f6f', '#56708a'], pattern: 'dots' },
      master: { name: 'Ebeveyn Yatak Odası', wall: ['#3d4a6e', '#5f3f55', '#3f5f5a'], pattern: 'damask' },
      kids: { name: 'Çocuk Odası', wall: ['#79b0d9', '#e2a3c2', '#9fd08a'], pattern: 'stars' },
      study: { name: 'Çalışma Odası', wall: ['#4e3d31', '#39473a', '#443a4f'], pattern: 'wood' },
      library: { name: 'Kütüphane', wall: ['#3c2d24', '#2f3a33'], pattern: 'wood' },
      bathroom: { name: 'Banyo', wall: ['#bfe0e6', '#d6e6f0', '#e9dfd2'], pattern: 'tiles' },
      hall: { name: 'Hol', wall: ['#8a7a66', '#6c7486'], pattern: 'stripes' },
      storage: { name: 'Depo', wall: ['#55524c', '#4a4f55'], pattern: 'brick' },
      wine: { name: 'Şarap Mahzeni', wall: ['#4b3328', '#3e2c2c'], pattern: 'brick' },
      workshop: { name: 'Atölye', wall: ['#4f5357', '#5a5047'], pattern: 'brick' },
      game: { name: 'Oyun Odası', wall: ['#2e3a5c', '#44305c'], pattern: 'stripes' },
      treasure: { name: 'Hazine Odası', wall: ['#5c2b2b', '#2b3a5c'], pattern: 'damask' },
      dressing: { name: 'Giyinme Odası', wall: ['#7a5a6e', '#6e6a5a'], pattern: 'dots' },
      music: { name: 'Müzik Odası', wall: ['#3b2f4f', '#2f4f4a'], pattern: 'stripes' },
      gallery: { name: 'Galeri', wall: ['#e8e4dc', '#d8d4cc', '#3a3f4a'], pattern: 'plain' },
      trophy: { name: 'Kupa Odası', wall: ['#1f4a2c', '#2a3a5a'], pattern: 'stripes' },
      gym: { name: 'Spor Salonu', wall: ['#4a5058', '#3a4a5a'], pattern: 'brick' },
      showroom: { name: 'Satış Salonu', wall: ['#2a1a2a', '#1a2a3a', '#3a2a1a'], pattern: 'damask' },
      techshow: { name: 'Mağaza Katı', wall: ['#e8eaf0', '#dde4ee'], pattern: 'plain' },
      office: { name: 'Ofis', wall: ['#c8c4b8', '#b8c0c8', '#a8a090'], pattern: 'stripes' },
      security: { name: 'Güvenlik Odası', wall: ['#4a5058', '#3a4048'], pattern: 'brick' },
      vault: { name: 'Kasa Dairesi', wall: ['#5a5e66', '#4a4e56'], pattern: 'plain' },
      lobby: { name: 'Giriş Holü', wall: ['#e0d8c8', '#d0c8b8'], pattern: 'damask' },
      exhibit: { name: 'Sergi Salonu', wall: ['#3a2e28', '#2a3a3a', '#4a3a2a'], pattern: 'plain' },
      cashier: { name: 'Vezne', wall: ['#d8d0c0', '#c8d0d8'], pattern: 'stripes' },
    },

    /* ------------------------------------------------------------------
     * SENARYO: Köprü altındaki brifingler
     * who: 'boss' (Reis), 'hero' (Red Crime)
     * ---------------------------------------------------------------- */
    BRIEFINGS: [
      [
        { who: 'boss', mood: 'grin', text: 'Ooo, Red Crime! Gel bakalım evlat. Soğuk mu? Şu varilin başına geç, ısın biraz.' },
        { who: 'hero', mood: 'normal', text: 'Reis... Aradığını duydum. İş varmış.' },
        { who: 'boss', mood: 'serious', text: 'İş var, hem de senin ilk işin. Mahallenin ucunda emekli bir öğretmen yaşıyor. İsim yok, sadece hedef: Emekli Öğretmen.' },
        { who: 'boss', mood: 'normal', text: 'Adam her gece dokuzda yatar. Yatak odası üst katta, kapısını kapatıp öyle uyur. Horultusunu sokaktan duyarsın.' },
        { who: 'hero', mood: 'normal', text: 'Evde ne var ki? Bir öğretmenden ne çıkar?' },
        { who: 'boss', mood: 'grin', text: 'Kırk yıl biriktirmiş evlat. Karısından kalma bilezikler, eski sikkeler, duvarda tablolar...' },
        { who: 'boss', mood: 'serious', text: 'Bir de küçük bir kasası varmış. Anahtarını evde bir yerde saklıyor, bankaya güvenmez.' },
        { who: 'hero', mood: 'worried', text: 'Ya uyanırsa?' },
        { who: 'boss', mood: 'angry', text: 'Uyanırsa ışıkları yakar, bütün evi oda oda arar, polisi arar. O yüzden uyanmayacak.' },
        { who: 'boss', mood: 'normal', text: 'Kamyonu kapının önüne çektirdim. Şoför süre dolana kadar bekler, sonra gazlar. Kimseyi beklemez.' },
        { who: 'hero', mood: 'happy', text: 'Beş dakika yeter. Sessiz, hızlı, temiz.' },
        { who: 'boss', mood: 'grin', text: 'İşte benim çocuğum! Hadi bakalım, yolun açık olsun.' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'Emekli Öğretmen hâlâ bileziklerini arıyormuş, hah! İyi iş çıkardın Red Crime.' },
        { who: 'boss', mood: 'serious', text: 'Sıradaki: Kasap. Dükkânın hasılatını her akşam eve götürüyor, bankaya uğramıyor.' },
        { who: 'hero', mood: 'normal', text: 'Evi nasıl bir yer?' },
        { who: 'boss', mood: 'normal', text: 'İki katlı eski bir ev. Kasap yatak odasının kapısını kilitler. Al şu matkabı ve maymuncuğu, kilit senin işin artık.' },
        { who: 'boss', mood: 'grin', text: 'Bu gece yağmur da yağıyor. Çatıdaki tıkırtıda seni kimse duymaz... pek.' },
        { who: 'hero', mood: 'happy', text: 'Yağmurlu gece, dolu kasa. Gidiyorum Reis.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Bu seferki farklı. Doktor. Yıllarca nöbet tutmuş, kuş uykusu uyur.' },
        { who: 'boss', mood: 'normal', text: 'Dubleks bir ev, altında da bodrum var. Bodruma salondaki kapaktan el merdiveniyle iniliyor.' },
        { who: 'hero', mood: 'normal', text: 'Bodrumda ne var?' },
        { who: 'boss', mood: 'grin', text: 'Şarap mahzeni, alet edevat... Söylentiye göre pahalı tıbbi cihazlar da orada. Kapıların çoğu kilitli, maymuncuğunu hazır tut.' },
        { who: 'boss', mood: 'angry', text: 'Kadının telefonu hep yanında. Seni görürse saniyesinde polisi arar, hesabını ona göre yap.' },
        { who: 'hero', mood: 'happy', text: 'Bir de sis var... Tam bizim hava.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Kuyumcu. Kapalıçarşı\'nın en zengin adamı. Dükkânı değil, evini soyacağız.' },
        { who: 'hero', mood: 'normal', text: 'Kuyumcunun evi... Kolay olmaz bu.' },
        { who: 'boss', mood: 'normal', text: 'Olmaz tabii. Adam geçen ay kamera taktırmış. Kameralar döner durur, önüne çıkarsan alarm öter.' },
        { who: 'boss', mood: 'grin', text: 'Ama kapının yanında bir alarm paneli var. Kablolarını çözersen bütün sistem susar.' },
        { who: 'boss', mood: 'serious', text: 'Alarm bir kere çaldı mı herkes uyanır, polis de yoldadır. Aklında olsun.' },
        { who: 'hero', mood: 'happy', text: 'Kameraların arkasından dolaşırım Reis.' },
        { who: 'boss', mood: 'grin', text: 'Bu arada, kazandığın parayla internetin karanlık köşelerinden güzel oyuncaklar alabilirsin. Benden duymadın.' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'Büyük balık zamanı Red Crime. Holding Patronu ve eşi.' },
        { who: 'boss', mood: 'serious', text: 'Dört katlı bir rezidans. Kavgalılarmış, ayrı katlarda, kilitli odalarda yatıyorlar. Biri kalkarsa öteki de kalkar.' },
        { who: 'hero', mood: 'worried', text: 'Dört kat... Aşağı taşıması uzun sürer.' },
        { who: 'boss', mood: 'normal', text: 'O yüzden gözün değerli olanda olsun. Saat, mücevher, nakit. Koltuk takımıyla uğraşma.' },
        { who: 'boss', mood: 'angry', text: 'Kameralar var, bir de koridorlardan birinde lazer ışınları. Kırmızı çizgiye değme, zıpla ya da eğil.' },
        { who: 'boss', mood: 'grin', text: 'Patronun kasası bu şehrin yarısından zengin diyorlar. Anahtarı evde bir yerde olmalı.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Koleksiyoncu. Adını bilmene gerek yok. Villası küçük bir müze gibi.' },
        { who: 'hero', mood: 'normal', text: 'Tablo mu çalacağız? Onları kim alır?' },
        { who: 'boss', mood: 'grin', text: 'Alan çok evlat, alan çok. Bir tanesi bizim köprüyü on kere satın alır.' },
        { who: 'boss', mood: 'normal', text: 'Lazerler bu evde yanıp sönüyor. Söndüğü anı kolla, geç. Kameralar her galeride.' },
        { who: 'boss', mood: 'serious', text: 'Koleksiyoncu uykusunda bile koleksiyonunu düşünür. Bir tablo yere düşerse fırlar yataktan.' },
        { who: 'hero', mood: 'happy', text: 'Eldivenlerimi giydim bile.' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'Golcü! Geçen hafta üç gol attı, bu hafta biz atacağız.' },
        { who: 'boss', mood: 'serious', text: 'Malikânenin koca bir bahçesi, havuzu var. Bahçede de bir bekçi köpeği dolaşıyor.' },
        { who: 'hero', mood: 'worried', text: 'Köpek... Havlarsa ne olacak?' },
        { who: 'boss', mood: 'angry', text: 'Havlarsa ev uyanır. Isırırsa elindekini düşürürsün. Çalıların arkasından git, havuzdan uzak dur.' },
        { who: 'boss', mood: 'normal', text: 'İçeride kupa dolapları, imzalı formalar, oyun konsolları... Golcü eşyalarına çok düşkün, kasası da bodrumda.' },
        { who: 'hero', mood: 'happy', text: 'Hazırım Reis. Top ayağımda.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Boğaz\'da bir yalı. Sahibi milletvekili, eşiyle birlikte orada kalıyor.' },
        { who: 'boss', mood: 'angry', text: 'Dikkat et: yalının bir özel güvenlik görevlisi var. Uyumaz, el feneriyle bütün gece devriye gezer.' },
        { who: 'hero', mood: 'worried', text: 'Uyumayan biri... Onu nasıl atlatacağım?' },
        { who: 'boss', mood: 'normal', text: 'Ritmini öğren. Nereden geçtiğini izle, arkasından dolaş. Görürse kovalar, yakalarsa oyun biter.' },
        { who: 'boss', mood: 'grin', text: 'Karanlık ağdan aldığın oyuncakları bu gece kullan. Sis bombası, uyku gazı... ne varsa.' },
        { who: 'hero', mood: 'happy', text: 'Gölge gibi girip çıkacağım.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Bu iş... büyük iş. Yurt dışından gelen bir milyarder: Oligark. Şehrin tepesindeki köşkte oturuyor.' },
        { who: 'boss', mood: 'angry', text: 'İki güvenlikçi, her köşede kamera, yanıp sönen lazerler. Kasası da bodrumdaki hazine odasında.' },
        { who: 'hero', mood: 'worried', text: 'Reis, bu intihar gibi...' },
        { who: 'boss', mood: 'normal', text: 'Değil. Alarm panelini hallet, güvenlikçilerin rotasını öğren, kilitleri sessizce aç. Adım adım.' },
        { who: 'boss', mood: 'grin', text: 'Bu işten sonra adın efsane olur Red Crime. Ya da hapiste yatarsın. İkisi de şöhret.' },
        { who: 'hero', mood: 'happy', text: 'Efsane olanı seçiyorum.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Ve... büyük final. Paşa Konağı.' },
        { who: 'boss', mood: 'serious', text: 'Koca bir bahçe, havuz, bahçe kulübesi. Üç kat artı bodrum. Bodrumda da hazine odası.' },
        { who: 'hero', mood: 'worried', text: 'Bahçede bir şey havlıyor gibi...' },
        { who: 'boss', mood: 'angry', text: 'Konağın bir bekçi köpeği var. Bir de iki bekçi, onlarca kamera ve şehrin en iyi alarm sistemi.' },
        { who: 'boss', mood: 'normal', text: 'Emekli Paşa ve eşi üst katlarda, kilitli odalarda yatıyor. Hizmetçiler bu gece izinli.' },
        { who: 'boss', mood: 'grin', text: 'Bu işi de bitirirsen köprü altından yalıya taşınıyoruz evlat. Son kez: sessiz, hızlı, temiz!' },
        { who: 'hero', mood: 'happy', text: 'Sessiz, hızlı, temiz!' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'Evlerle işimiz bitti Red Crime. Artık dükkân soyuyoruz. İlk durak: Altın Sarayı Kuyumcusu.' },
        { who: 'hero', mood: 'normal', text: 'Kuyumcu mu? Oralar kale gibidir Reis.' },
        { who: 'boss', mood: 'serious', text: 'Kale değil ama yakın. Vitrinlerin önünde hareket sensörleri var: ayakta yürürsen öterler. Eğilerek geç.' },
        { who: 'boss', mood: 'normal', text: 'Bir de yere gömülü basınç plakaları. Parlak metal bir şey görürsen üstünden atla.' },
        { who: 'boss', mood: 'grin', text: 'Gece bekçisi güvenlik odasında horul horul uyur. Kiralık kasalar bodrumda, çekmece çekmece altın.' },
        { who: 'hero', mood: 'happy', text: 'Eğilerek, atlayarak, sessizce. Anlaşıldı.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Tarih Müzesi. Bu gece altın maske ve kraliyet tacı sergiden sökülüyor... bizim tarafımızdan.' },
        { who: 'hero', mood: 'worried', text: 'Müzeler lazerle dolu olur ama...' },
        { who: 'boss', mood: 'normal', text: 'Hem de ne lazer. Bazıları galeriyi bir uçtan bir uca tarıyor. Işının arkasından yürü, yetişmesine izin verme.' },
        { who: 'boss', mood: 'angry', text: 'Bir bekçi devriye geziyor, bir tanesi de güvenlik odasında uyuyor. İkisine de görünme.' },
        { who: 'hero', mood: 'happy', text: 'Tarih yazacağız Reis.' },
        { who: 'boss', mood: 'grin', text: 'Tarih çalacağız evlat. Fark ince.' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'TeknoPark. Şehrin en büyük elektronik mağazası. Telefonlar, dizüstüler, konsollar... Hepsi yeni, hepsi kutulu.' },
        { who: 'hero', mood: 'normal', text: 'Elektronik ağırdır ama değerlidir.' },
        { who: 'boss', mood: 'serious', text: 'Küçükleri çuvala, büyükleri kamyona. Müdürün kasası üst katta, deposu bodrumda.' },
        { who: 'boss', mood: 'angry', text: 'İki bekçi var bu sefer. Biri devriye, biri güvenlik odasında. Kameralar her reyonda.' },
        { who: 'hero', mood: 'happy', text: 'Bu gece herkese bedava alışveriş.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Red Crime. Artık oyun bitti. Banka soyacağız.' },
        { who: 'hero', mood: 'worried', text: 'Banka mı?! Reis, bu başka lig...' },
        { who: 'boss', mood: 'normal', text: 'O yüzden yalnız gitmiyorsun. Ekibi topladım: bir hacker, bir gözcü, bir şoför ve bir dikkat dağıtıcı. İsim yok, sadece iş.' },
        { who: 'boss', mood: 'serious', text: 'Planı sen yapacaksın. Nereden gireceksin, kim nerede duracak, kasayı neyle açacaksın. Her seçimin bir bedeli var.' },
        { who: 'boss', mood: 'angry', text: 'Bir kere alarm çaldı mı banka kilitlenir, polis bir dakikada gelir. Yanlış hesap yapma.' },
        { who: 'hero', mood: 'normal', text: 'Planı görmek istiyorum. Her köşesini.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Red Crime... Otur şuraya. Sana hiç anlatmadım, neden köprü altında yaşadığımı.' },
        { who: 'boss', mood: 'serious', text: 'Yıllar önce Tefeci\'ye borçlandım. Ödeyemedim. Her şeyimi aldı. Şimdi de süre verdi: bu hafta.' },
        { who: 'hero', mood: 'worried', text: 'Ne kadar borç Reis?' },
        { who: 'boss', mood: 'angry', text: 'Bir bankanın kasası kadar. O yüzden Hazine Bankası. Genel müdürlük. Şehrin kalbi.' },
        { who: 'boss', mood: 'serious', text: 'Üç bekçi, onlarca kamera, tarayan lazerler, dev bir kasa. Ekip hazır, plan senin.' },
        { who: 'boss', mood: 'angry', text: 'Ve dinle beni iyi: iki hakkın var. İkisinde de olmazsa... Tefeci ikimizi de bulur. Ben de onu beklemem.' },
        { who: 'hero', mood: 'worried', text: 'Anlıyorum Reis. İki hak.' },
        { who: 'boss', mood: 'normal', text: 'Sen benim en iyi adamımsın evlat. Bunu hiç unutma. Şimdi git ve efsane ol.' },
      ],
    ],

    /* Reis'in her brifingin sonunda söylediği hedef cümlesi */
    TARGET_LINE: 'Bu işten en az {v} değerinde mal çıkarman lazım. Çıkaramazsan anlaşmamız feshedilir.',

    /* ------------------------------------------------------------------
     * EKİP (banka soygunları)
     * ---------------------------------------------------------------- */
    CREW: [
      { id: 'hacker', name: 'Hacker', role: 'Hacker', color: '#3ddc84', hat: 'cap', hatColor: '#1a1a1a' },
      { id: 'lookout', name: 'Gözcü', role: 'Gözcü', color: '#ffc83d', hat: 'fedora', hatColor: '#3a2a1a' },
      { id: 'driver', name: 'Şoför', role: 'Şoför', color: '#4aa8ff', hat: 'cap', hatColor: '#2a4d8f' },
      { id: 'decoy', name: 'Dikkat Dağıtıcı', role: 'Dikkat Dağıtıcı', color: '#ff8c2e', hat: 'none', hatColor: '#000' },
    ],
    PLAN: [
      {
        id: 'entry',
        title: 'Giriş Noktası',
        crew: null,
        options: [
          { id: 'front', name: 'Ön kapı', desc: 'Klasik giriş. Kamyonun yanından başlarsın.' },
          { id: 'roof', name: 'Çatı', desc: 'Çatıdan en üst kata süzülürsün. Ganimeti aşağı taşımak uzun sürer.' },
          { id: 'sewer', name: 'Kanalizasyon', desc: 'Doğrudan bodruma, kasa dairesinin yanına çıkarsın.' },
        ],
      },
      {
        id: 'hacker',
        title: 'Hacker',
        crew: 'hacker',
        options: [
          { id: 'cams', name: 'Kameraları kör et', desc: 'İlk 90 saniye boyunca tüm kameralar kapalı.' },
          { id: 'lasers', name: 'Lazer ve plakaları kapat', desc: 'Lazerler, tarayan ışınlar ve basınç plakaları baştan devre dışı.' },
          { id: 'panel', name: 'Alarm sistemine sız', desc: '2 dakika sonra bütün güvenlik sistemi kapanır.' },
        ],
      },
      {
        id: 'lookout',
        title: 'Gözcü',
        crew: 'lookout',
        options: [
          { id: 'roof', name: 'Karşı çatıda', desc: 'Bekçileri haritada gösterir, yaklaşınca telsizle uyarır.' },
          { id: 'street', name: 'Sokak başında', desc: 'Polisi yanlış adrese yollar: polis 25 saniye geç gelir.' },
        ],
      },
      {
        id: 'driver',
        title: 'Şoför',
        crew: 'driver',
        options: [
          { id: 'front', name: 'Ön cadde', desc: 'Kamyon ana girişin önünde bekler.' },
          { id: 'back', name: 'Arka sokak', desc: 'Kamyon binanın arkasında bekler; arka kapı açık olur.' },
        ],
      },
      {
        id: 'decoy',
        title: 'Dikkat Dağıtıcı',
        crew: 'decoy',
        options: [
          { id: 'call', name: 'Sahte ihbar', desc: 'Bekçiler ilk 45 saniye binanın önüne çıkar.' },
          { id: 'none', name: 'Yedekte bekle', desc: 'Dikkat Dağıtıcı arabada bekler. Soygun sonunda +%10 ganimet bonusu.' },
        ],
      },
      {
        id: 'gear',
        title: 'Kasa Ekipmanı',
        crew: null,
        options: [
          { id: 'drill', name: 'Termik matkap', desc: 'Kasa daha kolay açılır ama her aşama gürültü yapar.' },
          { id: 'stetho', name: 'Stetoskop', desc: 'Tamamen sessiz, ama kasa daha zor ve daha çok aşamalı.' },
        ],
      },
    ],

    /* Ev sahiplerinin replikleri */
    LINES: {
      stir: ['Hıı...?', 'Mmm...', 'Ne o...', '*horr*... hm?', 'Kedi mi o...'],
      wake: ['Kim var orada?!', 'Bu ses de ne?!', 'Hırsız mı var?!', 'Kalk bakalım...', 'Ne oluyor?!'],
      investigate: ['Buradan geldi...', 'Biri mi var?', 'Hmm...', 'Kim o?', 'Çıkın ortaya!'],
      search: ['Neredesin?', 'Saklanma!', 'Bir yerlerdesin...', 'Buldum seni... ya da?', 'Hmmm...'],
      spot: ['HIRSIZ!', 'Dur orada!', 'Yakaladım seni!', 'Polis! Polis!', 'Gel buraya!'],
      giveUp: ['Herhalde rüzgârdı...', 'Kedi olmalı...', 'Yaşlandım galiba...', 'Rüya gördüm herhalde...', 'Yine uyuyamayacağım...'],
      broken: ['Vazom!', 'O antikaydı!', 'Eyvah!', 'Ne kırıldı?!'],
      police: ['Alo, polis?!', 'Evde hırsız var!', '155! Hemen gelin!'],
      lost: ['Kaçtı!', 'Nereye gitti?', 'Kayboldu...'],
      sweep: ['Bütün evi arayacağım!', 'Bir yerlerde saklanıyorsun...', 'Oda oda bakacağım!', 'Çık ortaya!'],
      door: ['Bu kapı neden açık?', 'Kapıyı kim açtı?'],
      guard: ['Devriye normal.', 'Burada bir şey yok.', 'Hmm... sessiz gece.', 'Merkez, her şey yolunda.'],
      alarm: ['ALARM!', 'Biri içeride!', 'Güvenlik ihlali!'],
      gas: ['Başım... dönüyor...', 'Çok... uykum...'],
    },

    HINTS: [
      'Çömelerek yürürsen neredeyse hiç ses çıkarmazsın.',
      'Küçük eşyalar çuvala girer; çuval dolunca kamyona boşalt.',
      'Epik ve efsanevi eşyalar hafifçe parlar.',
      'Ev sahibi uyanınca ışıkları açar. Karanlıkta saklanmak çok daha kolay.',
      'Bir eşyayı Q ile fırlatıp ev sahibini başka yere yönlendirebilirsin.',
      'Kırılabilir eşyaları düşürme: vazo, kadeh, ayna...',
      'Açık renkli tahtalar gıcırdar. Üstlerinde çömel.',
      'Kasa anahtarı genelde başka bir odadadır.',
      'SHIFT ile koşarsın ama koşmak çok ses çıkarır.',
      'F ile el fenerini açıp kapatabilirsin; karanlıkta kapalı fener seni daha zor fark ettirir.',
      'Polis çağrılırsa süre azalır. Kamyona koş!',
      'Uyuyan birinin yüzüne el feneri tutma.',
      'Ağır eşyalar seni yavaşlatır ve daha sesli yürürsün.',
      'M tuşu ile evin haritasını açabilirsin.',
    ],
  };

  /**
   * Bölümün soygun süresi (saniye, zorluk çarpanı hariç). İlk üç bölüm sabit;
   * sonrakiler 10 dk'dan son bölümde 15 dk'ya doğrusal çıkar (30 sn'ye yuvarlı).
   */
  Config.heistTime = (levelIndex) => {
    const fixed = Config.HEIST_TIMES;
    if (levelIndex < fixed.length) return fixed[Math.max(0, levelIndex)];
    const first = fixed.length;
    const last = Config.LEVELS.length - 1;
    const k = last > first ? (levelIndex - first + 1) / (last - first + 1) : 1;
    const base = fixed[fixed.length - 1];
    const sec = base + (Config.HEIST_TIME_MAX - base) * Math.min(1, k);
    return Math.round(sec / 30) * 30;
  };

  RC.Config = Config;
})(window.RC);
