/* =========================================================================
 *  RED CRIME - Oyun yapılandırması
 *  Sabitler, bölüm tanımları, geliştirmeler ve senaryo metinleri.
 * ========================================================================= */
(function (RC) {
  'use strict';

  const Config = {
    VIEW_H: 720, // mantıksal görüş yüksekliği
    MIN_VIEW_W: 960,

    // Dünya ölçüleri
    FLOOR_H: 300, // bir katın yüksekliği (döşemeden döşemeye)
    SLAB: 24, // döşeme kalınlığı
    WALL: 24, // dış duvar kalınlığı
    DOOR_H: 150, // kapı boşluğu yüksekliği
    STEP_H: 20,
    STEP_W: 28,
    GRAVITY: 1900,
    STEP_UP: 22,
    STREET_W: 900,

    HEIST_TIME: 300, // 5 dakika
    FINAL_ATTEMPTS: 2,
    DEVELOPER: 'Red Crime Studio', // geliştirici adı (jenerikte görünür)

    FONT_TITLE: '"Bungee", "Impact", "Arial Black", sans-serif',
    FONT_UI: '"Rubik", "Segoe UI", "Helvetica Neue", Arial, sans-serif',
    FONT_MONO: '"Share Tech Mono", "Courier New", monospace',

    COLORS: {
      red: '#e8283c',
      redDark: '#8f1020',
      gold: '#ffc83d',
      night: '#070914',
      panel: '#12162a',
      panelLight: '#1d2340',
      text: '#f2f4ff',
      textDim: '#9aa3c7',
      green: '#3ddc84',
      blue: '#4aa8ff',
      purple: '#b467ff',
      orange: '#ff8c2e',
    },

    RARITY: [
      { id: 'common', name: 'Sıradan', mult: 1, color: '#d8dcef', chance: 0.72 },
      { id: 'rare', name: 'Nadir', mult: 2.2, color: '#4aa8ff', chance: 0.19 },
      { id: 'epic', name: 'Epik', mult: 4.5, color: '#b467ff', chance: 0.075 },
      { id: 'legendary', name: 'Efsanevi', mult: 11, color: '#ffc83d', chance: 0.015 },
    ],

    DIFFICULTY: {
      easy: { name: 'Kolay', hearing: 0.65, sight: 0.75, speed: 0.85, time: 1.2, decay: 1.4 },
      normal: { name: 'Normal', hearing: 1, sight: 1, speed: 1, time: 1, decay: 1 },
      hard: { name: 'Zor', hearing: 1.4, sight: 1.25, speed: 1.12, time: 0.85, decay: 0.7 },
    },

    /* ------------------------------------------------------------------
     * BÖLÜMLER
     * ---------------------------------------------------------------- */
    LEVELS: [
      {
        id: 1,
        name: 'Emekli Öğretmenin Evi',
        short: 'Küçük İki Katlı Ev',
        desc: 'Mahallenin sessiz köşesinde iki katlı, sevimli bir ev. Emekli öğretmen Nuri Hoca üst kattaki yatak odasında, kapısı kapalı uyur.',
        floors: 2,
        basement: false,
        width: 2700,
        garden: 420,
        residents: [{ name: 'Nuri Hoca', color: '#6f8fd6', cap: '#e8e0c8', mustache: true, sleepDepth: 1.0 }],
        dog: false,
        items: 240,
        target: 12000,
        stars: [12000, 24000, 40000],
        seed: 1107,
        facade: '#b9876a',
        roof: '#7a3b2e',
        theme: 'cozy',
        pool: false,
        shed: false,
        truckColor: '#c23a2b',
        weather: 'clear',
        bedroomLocked: false,
        lockedDoors: 0,
        closedDoors: 1,
        security: { cameras: 0, lasers: 0, panel: false, guards: 0, blink: false },
      },
      {
        id: 2,
        name: 'Kasap Rıza\'nın Evi',
        short: 'Eski İki Katlı Ev',
        desc: 'Kasap Rıza dükkânın hasılatını eve getirir. Yatak odasının kapısını hep kilitler; eski evin merdivenleri ve döşemesi gıcırdar.',
        floors: 2,
        basement: false,
        width: 3200,
        garden: 520,
        residents: [{ name: 'Rıza Usta', color: '#c94f4f', cap: '#f0f0f0', mustache: true, sleepDepth: 0.95 }],
        dog: false,
        items: 384,
        target: 25000,
        stars: [25000, 50000, 85000],
        seed: 2213,
        facade: '#d8c9a7',
        roof: '#44526b',
        theme: 'classic',
        pool: false,
        shed: false,
        truckColor: '#2b6cc2',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 1,
        closedDoors: 2,
        security: { cameras: 0, lasers: 0, panel: false, guards: 0, blink: false },
      },
      {
        id: 3,
        name: 'Doktor Selin\'in Dubleksi',
        short: 'Dubleks + Bodrum',
        desc: 'Modern bir dubleks ve gizemli bir bodrum. Doktor Selin kuş uykusu uyur; çalışma odası ve bodrum kilitlidir.',
        floors: 2,
        basement: true,
        width: 2900,
        garden: 640,
        residents: [{ name: 'Dr. Selin', color: '#3fae9a', cap: '#f6c1d8', mustache: false, sleepDepth: 0.85 }],
        dog: false,
        items: 896,
        target: 70000,
        stars: [70000, 140000, 230000],
        seed: 3371,
        facade: '#e6e6e6',
        roof: '#2e2e36',
        theme: 'modern',
        pool: false,
        shed: false,
        truckColor: '#2e9e5b',
        weather: 'fog',
        bedroomLocked: true,
        lockedDoors: 2,
        closedDoors: 2,
        security: { cameras: 0, lasers: 0, panel: false, guards: 0, blink: false },
      },
      {
        id: 4,
        name: 'Kuyumcu Zeki\'nin Evi',
        short: 'İki Kat + Bodrum · Kameralar',
        desc: 'Kapalıçarşı\'nın en zengin kuyumcusu. Evinde ilk kez güvenlik kameraları ve bir alarm sistemi var. Kamera seni görürse alarm çalar!',
        floors: 2,
        basement: true,
        width: 3000,
        garden: 600,
        residents: [{ name: 'Zeki Usta', color: '#c9a24a', cap: '#8a1b2a', mustache: true, sleepDepth: 0.9 }],
        dog: false,
        items: 960,
        target: 90000,
        stars: [90000, 170000, 280000],
        seed: 4421,
        facade: '#c8b8a0',
        roof: '#3a2a22',
        theme: 'classic',
        pool: false,
        shed: false,
        truckColor: '#b8861a',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 2,
        closedDoors: 2,
        security: { cameras: 3, lasers: 0, panel: true, guards: 0, blink: false },
      },
      {
        id: 5,
        name: 'Holding Patronunun Rezidansı',
        short: 'Dört Katlı Rezidans',
        desc: 'Dört kat, iki sakin, kameralar ve ilk lazer alarmı. Hakan Bey ve Leyla Hanım ayrı katlarda, kilitli odalarda uyur.',
        floors: 4,
        basement: false,
        width: 3200,
        garden: 560,
        residents: [
          { name: 'Hakan Bey', color: '#39406b', cap: '#ffd76a', mustache: true, sleepDepth: 0.9 },
          { name: 'Leyla Hanım', color: '#a54fa0', cap: '#ffe3f2', mustache: false, sleepDepth: 0.85 },
        ],
        dog: false,
        items: 1040,
        target: 120000,
        stars: [120000, 220000, 360000],
        seed: 4409,
        facade: '#9a8f86',
        roof: '#23262f',
        theme: 'luxury',
        pool: false,
        shed: false,
        truckColor: '#6b3cc2',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 3,
        closedDoors: 3,
        security: { cameras: 4, lasers: 2, panel: true, guards: 0, blink: false },
      },
      {
        id: 6,
        name: 'Koleksiyoncunun Galeri Villası',
        short: 'Üç Katlı Sanat Villası',
        desc: 'Ünlü sanat koleksiyoncusu Madam Nevra\'nın villası bir müze gibi: duvarlarda başyapıtlar, koridorlarda lazerler, köşelerde kameralar.',
        floors: 3,
        basement: false,
        width: 3300,
        garden: 900,
        residents: [{ name: 'Madam Nevra', color: '#7a3a6a', cap: '#f0e0ff', mustache: false, sleepDepth: 0.85 }],
        dog: false,
        items: 1280,
        target: 180000,
        stars: [180000, 330000, 520000],
        seed: 6613,
        facade: '#f2efe8',
        roof: '#34384a',
        theme: 'gallery',
        pool: false,
        shed: false,
        truckColor: '#e8e8ec',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 4,
        closedDoors: 3,
        security: { cameras: 6, lasers: 5, panel: true, guards: 0, blink: true },
      },
      {
        id: 7,
        name: 'Yıldız Futbolcunun Malikânesi',
        short: 'Havuzlu Malikâne + Köpek',
        desc: 'Süper Lig\'in yıldız golcüsü Kaan\'ın malikânesi. Havuz, oyun odası, kupa dolapları... ve bahçede bekçi köpeği Duman.',
        floors: 3,
        basement: true,
        width: 3400,
        garden: 1800,
        residents: [{ name: 'Kaan', color: '#2a8a4a', cap: '#ffffff', mustache: false, sleepDepth: 0.8 }],
        dog: true,
        dogName: 'Duman',
        items: 1600,
        target: 240000,
        stars: [240000, 440000, 700000],
        seed: 7717,
        facade: '#e0dcd4',
        roof: '#2a3a4a',
        theme: 'sport',
        pool: true,
        shed: false,
        truckColor: '#1f7a4a',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 4,
        closedDoors: 4,
        security: { cameras: 7, lasers: 5, panel: true, guards: 0, blink: true, motion: 1, plates: 0, sweepers: 0 },
      },
      {
        id: 8,
        name: 'Milletvekilinin Boğaz Yalısı',
        short: 'Yalı + Özel Güvenlik',
        desc: 'Boğaz kıyısında tarihi bir yalı. Artık bir özel güvenlik görevlisi de var: uyumaz, el feneriyle devriye gezer.',
        floors: 3,
        basement: true,
        width: 3600,
        garden: 1300,
        residents: [
          { name: 'Vekil Bey', color: '#5a4a3a', cap: '#e8e0c8', mustache: true, sleepDepth: 0.85 },
          { name: 'Vekil Hanım', color: '#8a5a7a', cap: '#ffe0f0', mustache: false, sleepDepth: 0.85 },
        ],
        dog: false,
        items: 1840,
        target: 320000,
        stars: [320000, 580000, 900000],
        seed: 8819,
        facade: '#e8dcc0',
        roof: '#5a2a22',
        theme: 'waterfront',
        pool: false,
        shed: true,
        truckColor: '#2a4d8f',
        weather: 'fog',
        bedroomLocked: true,
        lockedDoors: 5,
        closedDoors: 4,
        security: { cameras: 8, lasers: 6, panel: true, guards: 1, blink: true, motion: 2, plates: 0, sweepers: 0 },
      },
      {
        id: 9,
        name: 'Oligarkın Köşkü',
        short: 'Beş Katlı Kale',
        desc: 'Yurt dışından gelen gizemli bir milyarderin köşkü. İki güvenlik görevlisi, yanıp sönen lazerler ve her köşede kamera. Hata affetmez.',
        floors: 4,
        basement: true,
        width: 3500,
        garden: 900,
        residents: [
          { name: 'Boris Bey', color: '#3a3a4a', cap: '#c0c4cc', mustache: true, sleepDepth: 0.8 },
          { name: 'Katya Hanım', color: '#8a2a4a', cap: '#ffe8f0', mustache: false, sleepDepth: 0.8 },
        ],
        dog: false,
        items: 2080,
        target: 420000,
        stars: [420000, 760000, 1150000],
        seed: 9923,
        facade: '#6a6a74',
        roof: '#1a1a22',
        theme: 'oligarch',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 7,
        closedDoors: 4,
        security: { cameras: 11, lasers: 9, panel: true, guards: 2, blink: true, motion: 3, plates: 2, sweepers: 0 },
      },
      {
        id: 10,
        name: 'Paşa Konağı',
        short: 'Dev Bahçeli Konak · Final',
        desc: 'Devasa bir bahçe, havuz, kulübe, bekçi köpeği Karabaş, iki bekçi, hazine odası ve şehrin en gelişmiş güvenlik sistemi. Büyük final!',
        floors: 3,
        basement: true,
        width: 4800,
        garden: 3200,
        residents: [
          { name: 'Paşa Bey', color: '#8a2d2d', cap: '#ffffff', mustache: true, sleepDepth: 0.85 },
          { name: 'Hanımefendi', color: '#2d6a8a', cap: '#ffd1e0', mustache: false, sleepDepth: 0.8 },
        ],
        dog: true,
        dogName: 'Karabaş',
        items: 2720,
        target: 550000,
        stars: [550000, 1000000, 1600000],
        seed: 5557,
        facade: '#efe4cf',
        roof: '#5b2a22',
        theme: 'mansion',
        pool: true,
        shed: true,
        truckColor: '#1f1f24',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 8,
        closedDoors: 5,
        security: { cameras: 13, lasers: 10, panel: true, guards: 2, blink: true, motion: 3, plates: 3, sweepers: 1 },
      },
      {
        id: 11,
        name: 'Altın Sarayı Kuyumcusu',
        short: 'Kuyumcu Soygunu',
        desc: 'Şehrin en büyük kuyumcusu. Vitrinler mücevher dolu, bodrumda kiralık kasalar. Hareket sensörleri ve basınç plakaları ilk kez karşında. Gece bekçisi güvenlik odasında uyukluyor.',
        kind: 'shop',
        sign: 'ALTIN SARAYI',
        floors: 2,
        basement: true,
        width: 2600,
        garden: 320,
        urban: true,
        roomPlan: { '-1': ['vault', 'storage'], 0: ['showroom', 'showroom', 'office'], 1: ['workshop', 'security', 'office'] },
        residents: [{ name: 'Gece Bekçisi Sadık', color: '#2a3a6a', cap: '#1b2a55', hat: 'police', mustache: true, sleepDepth: 0.85, bedType: 'cot' }],
        dog: false,
        items: 1120,
        target: 650000,
        stars: [650000, 1100000, 1700000],
        seed: 11011,
        facade: '#3a2a22',
        roof: '#1a1a1e',
        theme: 'luxury',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 3,
        closedDoors: 1,
        security: { cameras: 8, lasers: 4, panel: true, guards: 0, blink: true, motion: 3, plates: 2, sweepers: 0 },
      },
      {
        id: 12,
        name: 'Şehir Tarih Müzesi',
        short: 'Müze Gecesi',
        desc: 'Üç katlı tarih müzesi: dinozor iskeletleri, altın maskeler, kraliyet tacı. Galerileri tarayan lazerler, basınç plakaları ve devriye gezen bir bekçi.',
        kind: 'museum',
        sign: 'TARİH MÜZESİ',
        floors: 3,
        basement: false,
        width: 3600,
        garden: 700,
        urban: true,
        roomPlan: { 0: ['lobby', 'exhibit', 'exhibit', 'exhibit', 'office'], 1: ['exhibit', 'gallery', 'exhibit', 'security'], 2: ['treasure', 'exhibit', 'gallery', 'office'] },
        residents: [{ name: 'Gece Bekçisi Nazım', color: '#3a4a3a', cap: '#1b2a55', hat: 'police', mustache: false, sleepDepth: 0.8, bedType: 'cot' }],
        dog: false,
        items: 1280,
        target: 800000,
        stars: [800000, 1400000, 2200000],
        seed: 12121,
        facade: '#d8d0c0',
        roof: '#3a3f4a',
        theme: 'gallery',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'fog',
        bedroomLocked: true,
        lockedDoors: 4,
        closedDoors: 2,
        security: { cameras: 10, lasers: 5, panel: true, guards: 1, blink: true, motion: 3, plates: 4, sweepers: 3 },
      },
      {
        id: 13,
        name: 'TeknoPark Mağazası',
        short: 'Dükkân Soygunu',
        desc: 'Şehrin en büyük elektronik mağazası: telefonlar, dizüstüler, konsollar. Deposu bodrumda, müdürün kasası üst katta. İki bekçi ve her rafta kamera.',
        kind: 'shop',
        sign: 'TEKNOPARK',
        floors: 2,
        basement: true,
        width: 3200,
        garden: 360,
        urban: true,
        roomPlan: { '-1': ['storage', 'storage', 'workshop'], 0: ['techshow', 'techshow', 'techshow', 'cashier'], 1: ['techshow', 'office', 'security', 'office'] },
        residents: [{ name: 'Gece Bekçisi Tayfun', color: '#4a2a2a', cap: '#1b2a55', hat: 'police', mustache: true, sleepDepth: 0.8, bedType: 'cot' }],
        dog: false,
        items: 1360,
        target: 900000,
        stars: [900000, 1500000, 2400000],
        seed: 13131,
        facade: '#2a3a5a',
        roof: '#15151a',
        theme: 'modern',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'clear',
        bedroomLocked: true,
        lockedDoors: 4,
        closedDoors: 2,
        security: { cameras: 11, lasers: 5, panel: true, guards: 2, blink: true, motion: 4, plates: 3, sweepers: 1 },
      },
      {
        id: 14,
        name: 'Anadolu Bankası Şubesi',
        short: 'Banka Soygunu · Planlı',
        desc: 'İlk banka işi. Ekibini topla, planı sen yap: giriş noktası, hacker, gözcü, şoför, dikkat dağıtıcı. Kiralık kasalar ve dev kasa bodrumda.',
        kind: 'bank',
        sign: 'ANADOLU BANKASI',
        floors: 2,
        basement: true,
        width: 3400,
        garden: 420,
        urban: true,
        planning: true,
        roomPlan: { '-1': ['vault', 'vault', 'storage'], 0: ['lobby', 'cashier', 'office', 'office'], 1: ['office', 'security', 'office', 'office'] },
        residents: [{ name: 'Gece Bekçisi Remzi', color: '#2a3a6a', cap: '#1b2a55', hat: 'police', mustache: true, sleepDepth: 0.75, bedType: 'cot' }],
        dog: false,
        items: 1360,
        target: 1300000,
        stars: [1300000, 2200000, 3500000],
        seed: 14141,
        facade: '#c8c0b0',
        roof: '#2a2a30',
        theme: 'oligarch',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 5,
        closedDoors: 2,
        security: { cameras: 13, lasers: 7, panel: true, guards: 2, blink: true, motion: 5, plates: 5, sweepers: 2 },
      },
      {
        id: 15,
        name: 'Hazine Bankası Genel Müdürlüğü',
        short: 'BÜYÜK VURGUN · 2 Hak',
        desc: 'Her şeyin sonu. Şehrin kalbindeki bankanın genel müdürlüğü. Üç bekçi, onlarca kamera, tarayan lazerler ve dev bir kasa. Sadece iki hakkın var.',
        kind: 'bank',
        sign: 'HAZİNE BANKASI',
        floors: 3,
        basement: true,
        width: 4600,
        garden: 600,
        urban: true,
        planning: true,
        final: true,
        roomPlan: { '-1': ['vault', 'vault', 'vault', 'storage'], 0: ['lobby', 'cashier', 'cashier', 'office', 'lobby'], 1: ['office', 'security', 'office', 'office', 'office'], 2: ['treasure', 'office', 'security', 'office'] },
        residents: [
          { name: 'Gece Bekçisi Kemal', color: '#2a3a6a', cap: '#1b2a55', hat: 'police', mustache: true, sleepDepth: 0.7, bedType: 'cot' },
          { name: 'Gece Bekçisi Oya', color: '#5a2a4a', cap: '#1b2a55', hat: 'police', mustache: false, sleepDepth: 0.7, bedType: 'cot' },
        ],
        dog: false,
        items: 1920,
        target: 2500000,
        stars: [2500000, 4000000, 6000000],
        seed: 15151,
        facade: '#b8b0a0',
        roof: '#1a1a1e',
        theme: 'oligarch',
        pool: false,
        shed: false,
        truckColor: '#15151a',
        weather: 'rain',
        bedroomLocked: true,
        lockedDoors: 7,
        closedDoors: 3,
        security: { cameras: 16, lasers: 9, panel: true, guards: 3, blink: true, motion: 6, plates: 6, sweepers: 4 },
      },
    ],

    /* ------------------------------------------------------------------
     * KARANLIK AĞ ÜRÜNLERİ (pahalı, özel ekipman)
     * perm: kalıcı ekipman · diğerleri: tüketilebilir (key: kısayol tuşu)
     * ---------------------------------------------------------------- */
    DARKWEB: [
      { id: 'lockpick', key: '1', name: 'Elektronik Maymuncuk', desc: 'Kilitli bir kapıyı saniyeler içinde, sessizce açar.', price: 18000, pack: 3, icon: 'key' },
      { id: 'jammer', key: '2', name: 'Kamera Karıştırıcı', desc: 'Evdeki tüm kameraları 25 saniye boyunca kör eder.', price: 30000, pack: 2, icon: 'eye' },
      { id: 'sleepgas', key: '3', name: 'Uyku Gazı Bombası', desc: 'Yakınındaki uyanık herkesi (köpek dahil) 25 saniye uyutur.', price: 45000, pack: 2, icon: 'zzz' },
      { id: 'smoke', key: '4', name: 'Sis Bombası', desc: 'Kalın bir duman bulutu: içindeyken kimse seni göremez.', price: 22000, pack: 2, icon: 'cloud' },
      { id: 'pistol', key: '6', name: 'Tabanca', desc: 'Çok pahalı. Havaya uyarı atışı: yakındaki herkes korkup kaçar, ama silah sesi 911\'i anında aratır.', price: 750000, pack: 3, icon: 'gun' },
      { id: 'emp', key: '5', name: 'EMP Cihazı', desc: 'Alarm sistemini, kameraları ve lazerleri tamamen devre dışı bırakır.', price: 70000, pack: 1, icon: 'bolt' },
      { id: 'nightvision', perm: true, name: 'Gece Görüş Gözlüğü', desc: 'Kalıcı. El feneri olmadan da karanlıkta çok daha geniş görürsün.', price: 90000, icon: 'eye' },
      { id: 'thermal', perm: true, name: 'Termal Tarayıcı', desc: 'Kalıcı. Duvarların ardındaki herkesi ve kasa anahtarını haritada gösterir.', price: 120000, icon: 'map' },
      { id: 'bribe', perm: true, name: 'Şoföre Rüşvet', desc: 'Kalıcı. Şoför Cemil her soygunda 45 saniye fazla bekler.', price: 75000, icon: 'truck' },
    ],

    /* ------------------------------------------------------------------
     * GELİŞTİRMELER (Dükkân)
     * ---------------------------------------------------------------- */
    UPGRADES: [
      {
        id: 'shoes',
        name: 'Kedi Pati Ayakkabı',
        desc: 'Ayak seslerini azaltır.',
        icon: 'shoe',
        costs: [4000, 12000, 30000],
        effect: (l) => RC.L('-%{v} ayak sesi', { v: l * 18 }),
      },
      {
        id: 'flashlight',
        name: 'Taktik El Feneri',
        desc: 'Daha uzun ve geniş ışık huzmesi.',
        icon: 'flashlight',
        costs: [3000, 9000, 22000],
        effect: (l) => RC.L('+%{v} menzil', { v: l * 20 }),
      },
      {
        id: 'bag',
        name: 'Büyük Çuval',
        desc: 'Cebe atılabilen küçük eşya kapasitesi.',
        icon: 'bag',
        costs: [5000, 15000, 40000],
        effect: (l) => RC.L('{v} küçük eşya', { v: 8 + l * 4 }),
      },
      {
        id: 'strength',
        name: 'Protein Tozu',
        desc: 'Ağır eşyalar seni daha az yavaşlatır.',
        icon: 'muscle',
        costs: [6000, 18000, 45000],
        effect: (l) => RC.L('-%{v} ağırlık cezası', { v: l * 15 }),
      },
      {
        id: 'safecracker',
        name: 'Kasa Ustası Kursu',
        desc: 'Kasa açma mini oyununda daha geniş hedef.',
        icon: 'safe',
        costs: [8000, 25000],
        effect: (l) => RC.L('+%{v} hedef bölge', { v: l * 35 }),
      },
      {
        id: 'lungs',
        name: 'Maraton Ciğeri',
        desc: 'Koşarken daha hızlısın.',
        icon: 'run',
        costs: [5000, 16000],
        effect: (l) => RC.L('+%{v} koşu hızı', { v: l * 8 }),
      },
    ],

    /* ------------------------------------------------------------------
     * ODA TİPLERİ
     * ---------------------------------------------------------------- */
    ROOM_TYPES: {
      living: { name: 'Salon', wall: ['#5d4a6e', '#4f5f7a', '#6e5a48', '#4d6b5b'], pattern: 'damask' },
      kitchen: { name: 'Mutfak', wall: ['#d9d2b8', '#c7dbd6', '#e0cfc0'], pattern: 'tiles' },
      dining: { name: 'Yemek Odası', wall: ['#7a4b43', '#5b6a4b', '#6a5577'], pattern: 'stripes' },
      bedroom: { name: 'Yatak Odası', wall: ['#4a5a82', '#6b4f6f', '#56708a'], pattern: 'dots' },
      master: { name: 'Ebeveyn Yatak Odası', wall: ['#3d4a6e', '#5f3f55', '#3f5f5a'], pattern: 'damask' },
      kids: { name: 'Çocuk Odası', wall: ['#79b0d9', '#e2a3c2', '#9fd08a'], pattern: 'stars' },
      study: { name: 'Çalışma Odası', wall: ['#4e3d31', '#39473a', '#443a4f'], pattern: 'wood' },
      library: { name: 'Kütüphane', wall: ['#3c2d24', '#2f3a33'], pattern: 'wood' },
      bathroom: { name: 'Banyo', wall: ['#bfe0e6', '#d6e6f0', '#e9dfd2'], pattern: 'tiles' },
      hall: { name: 'Hol', wall: ['#8a7a66', '#6c7486'], pattern: 'stripes' },
      storage: { name: 'Depo', wall: ['#55524c', '#4a4f55'], pattern: 'brick' },
      wine: { name: 'Şarap Mahzeni', wall: ['#4b3328', '#3e2c2c'], pattern: 'brick' },
      workshop: { name: 'Atölye', wall: ['#4f5357', '#5a5047'], pattern: 'brick' },
      game: { name: 'Oyun Odası', wall: ['#2e3a5c', '#44305c'], pattern: 'stripes' },
      treasure: { name: 'Hazine Odası', wall: ['#5c2b2b', '#2b3a5c'], pattern: 'damask' },
      dressing: { name: 'Giyinme Odası', wall: ['#7a5a6e', '#6e6a5a'], pattern: 'dots' },
      music: { name: 'Müzik Odası', wall: ['#3b2f4f', '#2f4f4a'], pattern: 'stripes' },
      gallery: { name: 'Galeri', wall: ['#e8e4dc', '#d8d4cc', '#3a3f4a'], pattern: 'plain' },
      trophy: { name: 'Kupa Odası', wall: ['#1f4a2c', '#2a3a5a'], pattern: 'stripes' },
      gym: { name: 'Spor Salonu', wall: ['#4a5058', '#3a4a5a'], pattern: 'brick' },
      showroom: { name: 'Satış Salonu', wall: ['#2a1a2a', '#1a2a3a', '#3a2a1a'], pattern: 'damask' },
      techshow: { name: 'Mağaza Katı', wall: ['#e8eaf0', '#dde4ee'], pattern: 'plain' },
      office: { name: 'Ofis', wall: ['#c8c4b8', '#b8c0c8', '#a8a090'], pattern: 'stripes' },
      security: { name: 'Güvenlik Odası', wall: ['#4a5058', '#3a4048'], pattern: 'brick' },
      vault: { name: 'Kasa Dairesi', wall: ['#5a5e66', '#4a4e56'], pattern: 'plain' },
      lobby: { name: 'Giriş Holü', wall: ['#e0d8c8', '#d0c8b8'], pattern: 'damask' },
      exhibit: { name: 'Sergi Salonu', wall: ['#3a2e28', '#2a3a3a', '#4a3a2a'], pattern: 'plain' },
      cashier: { name: 'Vezne', wall: ['#d8d0c0', '#c8d0d8'], pattern: 'stripes' },
    },

    /* ------------------------------------------------------------------
     * SENARYO: Köprü altındaki brifingler
     * who: 'boss' (Reis), 'hero' (Topaç)
     * ---------------------------------------------------------------- */
    BRIEFINGS: [
      [
        { who: 'boss', mood: 'grin', text: 'Ooo, Topaç! Gel bakalım evlat. Soğuk mu? Şu varilin başına geç, ısın biraz.' },
        { who: 'hero', mood: 'normal', text: 'Reis... Aradığını duydum. İş varmış.' },
        { who: 'boss', mood: 'serious', text: 'İş var, hem de senin ilk işin. Mahallenin ucunda emekli bir öğretmen yaşıyor: Nuri Hoca.' },
        { who: 'boss', mood: 'normal', text: 'Adam her gece dokuzda yatar. Yatak odası üst katta, kapısını kapatıp öyle uyur. Horultusunu sokaktan duyarsın.' },
        { who: 'hero', mood: 'normal', text: 'Evde ne var ki? Bir öğretmenden ne çıkar?' },
        { who: 'boss', mood: 'grin', text: 'Kırk yıl biriktirmiş evlat. Karısından kalma bilezikler, eski sikkeler, duvarda tablolar...' },
        { who: 'boss', mood: 'serious', text: 'Bir de küçük bir kasası varmış. Anahtarını evde bir yerde saklıyor, bankaya güvenmez.' },
        { who: 'hero', mood: 'worried', text: 'Ya uyanırsa?' },
        { who: 'boss', mood: 'angry', text: 'Uyanırsa ışıkları yakar, bütün evi oda oda arar, polisi arar. O yüzden uyanmayacak.' },
        { who: 'boss', mood: 'normal', text: 'Kamyonu kapının önüne çektirdim. Şoför Cemil beş dakika bekler, sonra gazlar. Kimseyi beklemez.' },
        { who: 'hero', mood: 'happy', text: 'Beş dakika yeter. Sessiz, hızlı, temiz.' },
        { who: 'boss', mood: 'grin', text: 'İşte benim çocuğum! Hadi bakalım, yolun açık olsun.' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'Nuri Hoca hâlâ bileziklerini arıyormuş, hah! İyi iş çıkardın Topaç.' },
        { who: 'boss', mood: 'serious', text: 'Sıradaki: Kasap Rıza. Dükkânın hasılatını her akşam eve götürüyor, bankaya uğramıyor.' },
        { who: 'hero', mood: 'normal', text: 'Evi nasıl bir yer?' },
        { who: 'boss', mood: 'normal', text: 'İki katlı eski bir ev. Rıza yatak odasının kapısını kilitler. Al şu maymuncuğu, kilit senin işin artık.' },
        { who: 'boss', mood: 'grin', text: 'Bu gece yağmur da yağıyor. Çatıdaki tıkırtıda seni kimse duymaz... pek.' },
        { who: 'hero', mood: 'happy', text: 'Yağmurlu gece, dolu kasa. Gidiyorum Reis.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Bu seferki farklı. Doktor Selin. Yıllarca nöbet tutmuş, kuş uykusu uyur.' },
        { who: 'boss', mood: 'normal', text: 'Dubleks bir ev, altında da bodrum var. Bodruma salondaki kapaktan el merdiveniyle iniliyor.' },
        { who: 'hero', mood: 'normal', text: 'Bodrumda ne var?' },
        { who: 'boss', mood: 'grin', text: 'Şarap mahzeni, alet edevat... Söylentiye göre pahalı tıbbi cihazlar da orada. Kapıların çoğu kilitli, maymuncuğunu hazır tut.' },
        { who: 'boss', mood: 'angry', text: 'Kadının telefonu hep yanında. Seni görürse saniyesinde polisi arar, hesabını ona göre yap.' },
        { who: 'hero', mood: 'happy', text: 'Bir de sis var... Tam bizim hava.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Kuyumcu Zeki. Kapalıçarşı\'nın en zengin adamı. Dükkânı değil, evini soyacağız.' },
        { who: 'hero', mood: 'normal', text: 'Kuyumcunun evi... Kolay olmaz bu.' },
        { who: 'boss', mood: 'normal', text: 'Olmaz tabii. Adam geçen ay kamera taktırmış. Kameralar döner durur, önüne çıkarsan alarm öter.' },
        { who: 'boss', mood: 'grin', text: 'Ama kapının yanında bir alarm paneli var. Kablolarını çözersen bütün sistem susar.' },
        { who: 'boss', mood: 'serious', text: 'Alarm bir kere çaldı mı herkes uyanır, polis de yoldadır. Aklında olsun.' },
        { who: 'hero', mood: 'happy', text: 'Kameraların arkasından dolaşırım Reis.' },
        { who: 'boss', mood: 'grin', text: 'Bu arada, kazandığın parayla internetin karanlık köşelerinden güzel oyuncaklar alabilirsin. Benden duymadın.' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'Büyük balık zamanı Topaç. Holding patronu Hakan Bey ve eşi Leyla Hanım.' },
        { who: 'boss', mood: 'serious', text: 'Dört katlı bir rezidans. Kavgalılarmış, ayrı katlarda, kilitli odalarda yatıyorlar. Biri kalkarsa öteki de kalkar.' },
        { who: 'hero', mood: 'worried', text: 'Dört kat... Aşağı taşıması uzun sürer.' },
        { who: 'boss', mood: 'normal', text: 'O yüzden gözün değerli olanda olsun. Saat, mücevher, nakit. Koltuk takımıyla uğraşma.' },
        { who: 'boss', mood: 'angry', text: 'Kameralar var, bir de koridorlardan birinde lazer ışınları. Kırmızı çizgiye değme, zıpla ya da eğil.' },
        { who: 'boss', mood: 'grin', text: 'Hakan Bey\'in kasası bu şehrin yarısından zengin diyorlar. Anahtarı evde bir yerde olmalı.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Madam Nevra. Sanat koleksiyoncusu. Villası küçük bir müze gibi.' },
        { who: 'hero', mood: 'normal', text: 'Tablo mu çalacağız? Onları kim alır?' },
        { who: 'boss', mood: 'grin', text: 'Alan çok evlat, alan çok. Bir tanesi bizim köprüyü on kere satın alır.' },
        { who: 'boss', mood: 'normal', text: 'Lazerler bu evde yanıp sönüyor. Söndüğü anı kolla, geç. Kameralar her galeride.' },
        { who: 'boss', mood: 'serious', text: 'Madam uykusunda bile koleksiyonunu düşünür. Bir tablo yere düşerse fırlar yataktan.' },
        { who: 'hero', mood: 'happy', text: 'Eldivenlerimi giydim bile.' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'Golcü Kaan! Geçen hafta üç gol attı, bu hafta biz atacağız.' },
        { who: 'boss', mood: 'serious', text: 'Malikânenin koca bir bahçesi, havuzu var. Bahçede de Duman diye bir köpek dolaşıyor.' },
        { who: 'hero', mood: 'worried', text: 'Köpek... Havlarsa ne olacak?' },
        { who: 'boss', mood: 'angry', text: 'Havlarsa ev uyanır. Isırırsa elindekini düşürürsün. Çalıların arkasından git, havuzdan uzak dur.' },
        { who: 'boss', mood: 'normal', text: 'İçeride kupa dolapları, imzalı formalar, oyun konsolları... Kaan eşyalarına çok düşkün, kasası da bodrumda.' },
        { who: 'hero', mood: 'happy', text: 'Hazırım Reis. Top ayağımda.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Boğaz\'da bir yalı. Sahibi milletvekili, eşiyle birlikte orada kalıyor.' },
        { who: 'boss', mood: 'angry', text: 'Dikkat et: yalının bir özel güvenlik görevlisi var. Uyumaz, el feneriyle bütün gece devriye gezer.' },
        { who: 'hero', mood: 'worried', text: 'Uyumayan biri... Onu nasıl atlatacağım?' },
        { who: 'boss', mood: 'normal', text: 'Ritmini öğren. Nereden geçtiğini izle, arkasından dolaş. Görürse kovalar, yakalarsa oyun biter.' },
        { who: 'boss', mood: 'grin', text: 'Karanlık ağdan aldığın oyuncakları bu gece kullan. Sis bombası, uyku gazı... ne varsa.' },
        { who: 'hero', mood: 'happy', text: 'Gölge gibi girip çıkacağım.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Bu iş... büyük iş. Yurt dışından gelen bir milyarder, Boris. Şehrin tepesindeki köşkte oturuyor.' },
        { who: 'boss', mood: 'angry', text: 'İki güvenlikçi, her köşede kamera, yanıp sönen lazerler. Kasası da bodrumdaki hazine odasında.' },
        { who: 'hero', mood: 'worried', text: 'Reis, bu intihar gibi...' },
        { who: 'boss', mood: 'normal', text: 'Değil. Alarm panelini hallet, güvenlikçilerin rotasını öğren, kilitleri sessizce aç. Adım adım.' },
        { who: 'boss', mood: 'grin', text: 'Bu işten sonra adın efsane olur Topaç. Ya da hapiste yatarsın. İkisi de şöhret.' },
        { who: 'hero', mood: 'happy', text: 'Efsane olanı seçiyorum.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Ve... büyük final. Paşa Konağı.' },
        { who: 'boss', mood: 'serious', text: 'Koca bir bahçe, havuz, bahçe kulübesi. Üç kat artı bodrum. Bodrumda da hazine odası.' },
        { who: 'hero', mood: 'worried', text: 'Bahçede bir şey havlıyor gibi...' },
        { who: 'boss', mood: 'angry', text: 'Karabaş! Konağın bekçi köpeği. Bir de iki bekçi, onlarca kamera ve şehrin en iyi alarm sistemi.' },
        { who: 'boss', mood: 'normal', text: 'Paşa Bey ve hanımı üst katlarda, kilitli odalarda yatıyor. Hizmetçiler bu gece izinli.' },
        { who: 'boss', mood: 'grin', text: 'Bu işi de bitirirsen köprü altından yalıya taşınıyoruz evlat. Son kez: sessiz, hızlı, temiz!' },
        { who: 'hero', mood: 'happy', text: 'Sessiz, hızlı, temiz!' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'Evlerle işimiz bitti Topaç. Artık dükkân soyuyoruz. İlk durak: Altın Sarayı Kuyumcusu.' },
        { who: 'hero', mood: 'normal', text: 'Kuyumcu mu? Oralar kale gibidir Reis.' },
        { who: 'boss', mood: 'serious', text: 'Kale değil ama yakın. Vitrinlerin önünde hareket sensörleri var: ayakta yürürsen öterler. Eğilerek geç.' },
        { who: 'boss', mood: 'normal', text: 'Bir de yere gömülü basınç plakaları. Parlak metal bir şey görürsen üstünden atla.' },
        { who: 'boss', mood: 'grin', text: 'Gece bekçisi Sadık, güvenlik odasında horul horul uyur. Kiralık kasalar bodrumda, çekmece çekmece altın.' },
        { who: 'hero', mood: 'happy', text: 'Eğilerek, atlayarak, sessizce. Anlaşıldı.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Tarih Müzesi. Bu gece altın maske ve kraliyet tacı sergiden sökülüyor... bizim tarafımızdan.' },
        { who: 'hero', mood: 'worried', text: 'Müzeler lazerle dolu olur ama...' },
        { who: 'boss', mood: 'normal', text: 'Hem de ne lazer. Bazıları galeriyi bir uçtan bir uca tarıyor. Işının arkasından yürü, yetişmesine izin verme.' },
        { who: 'boss', mood: 'angry', text: 'Bir bekçi devriye geziyor, bir tanesi de güvenlik odasında uyuyor. İkisine de görünme.' },
        { who: 'hero', mood: 'happy', text: 'Tarih yazacağız Reis.' },
        { who: 'boss', mood: 'grin', text: 'Tarih çalacağız evlat. Fark ince.' },
      ],
      [
        { who: 'boss', mood: 'grin', text: 'TeknoPark. Şehrin en büyük elektronik mağazası. Telefonlar, dizüstüler, konsollar... Hepsi yeni, hepsi kutulu.' },
        { who: 'hero', mood: 'normal', text: 'Elektronik ağırdır ama değerlidir.' },
        { who: 'boss', mood: 'serious', text: 'Küçükleri çuvala, büyükleri kamyona. Müdürün kasası üst katta, deposu bodrumda.' },
        { who: 'boss', mood: 'angry', text: 'İki bekçi var bu sefer. Biri devriye, biri güvenlik odasında. Kameralar her reyonda.' },
        { who: 'hero', mood: 'happy', text: 'Bu gece herkese bedava alışveriş.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Topaç. Artık oyun bitti. Banka soyacağız.' },
        { who: 'hero', mood: 'worried', text: 'Banka mı?! Reis, bu başka lig...' },
        { who: 'boss', mood: 'normal', text: 'O yüzden yalnız gitmiyorsun. Ekibi topladım: Fare hacker, Kartal gözcü, Cemil şoför, Şimşek de dikkat dağıtıcı.' },
        { who: 'boss', mood: 'serious', text: 'Planı sen yapacaksın. Nereden gireceksin, kim nerede duracak, kasayı neyle açacaksın. Her seçimin bir bedeli var.' },
        { who: 'boss', mood: 'angry', text: 'Bir kere alarm çaldı mı banka kilitlenir, polis bir dakikada gelir. Yanlış hesap yapma.' },
        { who: 'hero', mood: 'normal', text: 'Planı görmek istiyorum. Her köşesini.' },
      ],
      [
        { who: 'boss', mood: 'serious', text: 'Topaç... Otur şuraya. Sana hiç anlatmadım, neden köprü altında yaşadığımı.' },
        { who: 'boss', mood: 'serious', text: 'Yıllar önce Kara Kemal\'e borçlandım. Ödeyemedim. Her şeyimi aldı. Şimdi de süre verdi: bu hafta.' },
        { who: 'hero', mood: 'worried', text: 'Ne kadar borç Reis?' },
        { who: 'boss', mood: 'angry', text: 'Bir bankanın kasası kadar. O yüzden Hazine Bankası. Genel müdürlük. Şehrin kalbi.' },
        { who: 'boss', mood: 'serious', text: 'Üç bekçi, onlarca kamera, tarayan lazerler, dev bir kasa. Ekip hazır, plan senin.' },
        { who: 'boss', mood: 'angry', text: 'Ve dinle beni iyi: iki hakkın var. İkisinde de olmazsa... Kara Kemal ikimizi de bulur. Ben de onu beklemem.' },
        { who: 'hero', mood: 'worried', text: 'Anlıyorum Reis. İki hak.' },
        { who: 'boss', mood: 'normal', text: 'Sen benim en iyi adamımsın evlat. Bunu hiç unutma. Şimdi git ve efsane ol.' },
      ],
    ],

    /* Reis'in her brifingin sonunda söylediği hedef cümlesi */
    TARGET_LINE: 'Bu işten en az {v} değerinde mal çıkarman lazım. Çıkaramazsan anlaşmamız feshedilir.',

    /* ------------------------------------------------------------------
     * EKİP (banka soygunları)
     * ---------------------------------------------------------------- */
    CREW: [
      { id: 'hacker', name: 'Fare', role: 'Hacker', color: '#3ddc84', hat: 'cap', hatColor: '#1a1a1a' },
      { id: 'lookout', name: 'Kartal', role: 'Gözcü', color: '#ffc83d', hat: 'fedora', hatColor: '#3a2a1a' },
      { id: 'driver', name: 'Cemil', role: 'Şoför', color: '#4aa8ff', hat: 'cap', hatColor: '#2a4d8f' },
      { id: 'decoy', name: 'Şimşek', role: 'Dikkat Dağıtıcı', color: '#ff8c2e', hat: 'none', hatColor: '#000' },
    ],
    PLAN: [
      {
        id: 'entry',
        title: 'Giriş Noktası',
        crew: null,
        options: [
          { id: 'front', name: 'Ön kapı', desc: 'Klasik giriş. Kamyonun yanından başlarsın.' },
          { id: 'roof', name: 'Çatı', desc: 'Çatıdan en üst kata süzülürsün. Ganimeti aşağı taşımak uzun sürer.' },
          { id: 'sewer', name: 'Kanalizasyon', desc: 'Doğrudan bodruma, kasa dairesinin yanına çıkarsın.' },
        ],
      },
      {
        id: 'hacker',
        title: 'Hacker: Fare',
        crew: 'hacker',
        options: [
          { id: 'cams', name: 'Kameraları kör et', desc: 'İlk 90 saniye boyunca tüm kameralar kapalı.' },
          { id: 'lasers', name: 'Lazer ve plakaları kapat', desc: 'Lazerler, tarayan ışınlar ve basınç plakaları baştan devre dışı.' },
          { id: 'panel', name: 'Alarm sistemine sız', desc: '2 dakika sonra bütün güvenlik sistemi kapanır.' },
        ],
      },
      {
        id: 'lookout',
        title: 'Gözcü: Kartal',
        crew: 'lookout',
        options: [
          { id: 'roof', name: 'Karşı çatıda', desc: 'Bekçileri haritada gösterir, yaklaşınca telsizle uyarır.' },
          { id: 'street', name: 'Sokak başında', desc: 'Polisi yanlış adrese yollar: polis 25 saniye geç gelir.' },
        ],
      },
      {
        id: 'driver',
        title: 'Şoför: Cemil',
        crew: 'driver',
        options: [
          { id: 'front', name: 'Ön cadde', desc: 'Kamyon ana girişin önünde bekler.' },
          { id: 'back', name: 'Arka sokak', desc: 'Kamyon binanın arkasında bekler; arka kapı açık olur.' },
        ],
      },
      {
        id: 'decoy',
        title: 'Dikkat Dağıtıcı: Şimşek',
        crew: 'decoy',
        options: [
          { id: 'call', name: 'Sahte ihbar', desc: 'Bekçiler ilk 45 saniye binanın önüne çıkar.' },
          { id: 'none', name: 'Yedekte bekle', desc: 'Şimşek arabada bekler. Soygun sonunda +%10 ganimet bonusu.' },
        ],
      },
      {
        id: 'gear',
        title: 'Kasa Ekipmanı',
        crew: null,
        options: [
          { id: 'drill', name: 'Termik matkap', desc: 'Kasa daha kolay açılır ama her aşama gürültü yapar.' },
          { id: 'stetho', name: 'Stetoskop', desc: 'Tamamen sessiz, ama kasa daha zor ve daha çok aşamalı.' },
        ],
      },
    ],

    /* Ev sahiplerinin replikleri */
    LINES: {
      stir: ['Hıı...?', 'Mmm...', 'Ne o...', '*horr*... hm?', 'Kedi mi o...'],
      wake: ['Kim var orada?!', 'Bu ses de ne?!', 'Hırsız mı var?!', 'Kalk bakalım...', 'Ne oluyor?!'],
      investigate: ['Buradan geldi...', 'Biri mi var?', 'Hmm...', 'Kim o?', 'Çıkın ortaya!'],
      search: ['Neredesin?', 'Saklanma!', 'Bir yerlerdesin...', 'Buldum seni... ya da?', 'Hmmm...'],
      spot: ['HIRSIZ!', 'Dur orada!', 'Yakaladım seni!', 'Polis! Polis!', 'Gel buraya!'],
      giveUp: ['Herhalde rüzgârdı...', 'Kedi olmalı...', 'Yaşlandım galiba...', 'Rüya gördüm herhalde...', 'Yine uyuyamayacağım...'],
      broken: ['Vazom!', 'O antikaydı!', 'Eyvah!', 'Ne kırıldı?!'],
      police: ['Alo, polis?!', 'Evde hırsız var!', '155! Hemen gelin!'],
      lost: ['Kaçtı!', 'Nereye gitti?', 'Kayboldu...'],
      sweep: ['Bütün evi arayacağım!', 'Bir yerlerde saklanıyorsun...', 'Oda oda bakacağım!', 'Çık ortaya!'],
      door: ['Bu kapı neden açık?', 'Kapıyı kim açtı?'],
      guard: ['Devriye normal.', 'Burada bir şey yok.', 'Hmm... sessiz gece.', 'Merkez, her şey yolunda.'],
      alarm: ['ALARM!', 'Biri içeride!', 'Güvenlik ihlali!'],
      gas: ['Başım... dönüyor...', 'Çok... uykum...'],
    },

    HINTS: [
      'Çömelerek yürürsen neredeyse hiç ses çıkarmazsın.',
      'Küçük eşyalar çuvala girer; çuval dolunca kamyona boşalt.',
      'Epik ve efsanevi eşyalar hafifçe parlar.',
      'Ev sahibi uyanınca ışıkları açar. Karanlıkta saklanmak çok daha kolay.',
      'Bir eşyayı Q ile fırlatıp ev sahibini başka yere yönlendirebilirsin.',
      'Kırılabilir eşyaları düşürme: vazo, kadeh, ayna...',
      'Açık renkli tahtalar gıcırdar. Üstlerinde çömel.',
      'Kasa anahtarı genelde başka bir odadadır.',
      'SHIFT ile koşarsın ama koşmak çok ses çıkarır.',
      'F ile el fenerini açıp kapatabilirsin; karanlıkta kapalı fener seni daha zor fark ettirir.',
      'Polis çağrılırsa süre azalır. Kamyona koş!',
      'Uyuyan birinin yüzüne el feneri tutma.',
      'Ağır eşyalar seni yavaşlatır ve daha sesli yürürsün.',
      'M tuşu ile evin haritasını açabilirsin.',
    ],
  };

  RC.Config = Config;
})(window.RC);
