/* =========================================================================
 *  RED CRIME - English translations
 *  Keys are the original Turkish texts; RC.L() looks them up at runtime.
 * ========================================================================= */
(function (RC) {
  'use strict';
  Object.assign(RC.I18N.EN, {
  "Dil": "Language",
  "Türkçe": "Türkçe",
  "Beceriksiz herif.": "Useless fool.",
  "Kamera": "Camera",
  "Lazer": "Laser",
  "Dikkat Dağıtıcı arabada bekler. Soygun sonunda +%10 ganimet bonusu.": "The Decoy waits in the car. +10% loot bonus at the end of the heist.",
  "Red Crime — sessiz, hızlı, temiz": "Red Crime — silent, fast, clean",
  "Hacker · Gözcü · Şoför · Dikkat Dağıtıcı": "The Hacker · The Lookout · The Driver · The Decoy",
  "Altın Sarayı Kuyumcusu": "Golden Palace Jewelers",
  "Kuyumcu Soygunu": "Jewelry Store Heist",
  "Şehrin en büyük kuyumcusu. Vitrinler mücevher dolu, bodrumda kiralık kasalar. Hareket sensörleri ve basınç plakaları ilk kez karşında. Gece bekçisi güvenlik odasında uyukluyor.": "The biggest jeweler in the city. Display cases full of jewels, safe deposit boxes in the basement. Motion sensors and pressure plates for the first time. The night watchman dozes in the security room.",
  "ALTIN SARAYI": "GOLDEN PALACE",
  "Şehir Tarih Müzesi": "City History Museum",
  "Müze Gecesi": "Night at the Museum",
  "Üç katlı tarih müzesi: dinozor iskeletleri, altın maskeler, kraliyet tacı. Galerileri tarayan lazerler, basınç plakaları ve devriye gezen bir bekçi.": "A three-story history museum: dinosaur skeletons, golden masks, a royal crown. Lasers sweeping the galleries, pressure plates and a patrolling guard.",
  "TARİH MÜZESİ": "HISTORY MUSEUM",
  "TeknoPark Mağazası": "TechnoPark Store",
  "Dükkân Soygunu": "Store Heist",
  "Şehrin en büyük elektronik mağazası: telefonlar, dizüstüler, konsollar. Deposu bodrumda, müdürün kasası üst katta. İki bekçi ve her rafta kamera.": "The city's biggest electronics store: phones, laptops, consoles. Stockroom in the basement, the manager's safe upstairs. Two guards and a camera on every aisle.",
  "TEKNOPARK": "TECHNOPARK",
  "Anadolu Bankası Şubesi": "Anatolian Bank Branch",
  "Banka Soygunu · Planlı": "Bank Heist · Planned",
  "İlk banka işi. Ekibini topla, planı sen yap: giriş noktası, hacker, gözcü, şoför, dikkat dağıtıcı. Kiralık kasalar ve dev kasa bodrumda.": "Your first bank job. Assemble your crew and make the plan: entry point, hacker, lookout, driver, decoy. Deposit boxes and the big vault are in the basement.",
  "ANADOLU BANKASI": "ANATOLIAN BANK",
  "Hazine Bankası Genel Müdürlüğü": "Treasury Bank Headquarters",
  "BÜYÜK VURGUN · 2 Hak": "THE BIG SCORE · 2 Tries",
  "Her şeyin sonu. Şehrin kalbindeki bankanın genel müdürlüğü. Üç bekçi, onlarca kamera, tarayan lazerler ve dev bir kasa. Sadece iki hakkın var.": "The end of everything. The headquarters of the bank in the heart of the city. Three guards, dozens of cameras, sweeping lasers and a giant vault. You only get two tries.",
  "HAZİNE BANKASI": "TREASURY BANK",
  "Tabanca": "Pistol",
  "Çok pahalı. Havaya uyarı atışı: yakındaki herkes korkup kaçar, ama silah sesi 911'i anında aratır.": "Very expensive. A warning shot into the air: everyone nearby panics and runs, but the gunshot gets 911 called instantly.",
  "Giriş Noktası": "Entry Point",
  "Ön kapı": "Front door",
  "Klasik giriş. Kamyonun yanından başlarsın.": "The classic entry. You start next to the truck.",
  "Çatı": "Roof",
  "Çatıdan en üst kata süzülürsün. Ganimeti aşağı taşımak uzun sürer.": "You slip in from the roof to the top floor. Hauling the loot down takes a while.",
  "Kanalizasyon": "Sewer",
  "Doğrudan bodruma, kasa dairesinin yanına çıkarsın.": "You come up straight into the basement, right next to the vault.",
  "Kameraları kör et": "Blind the cameras",
  "İlk 90 saniye boyunca tüm kameralar kapalı.": "All cameras are off for the first 90 seconds.",
  "Lazer ve plakaları kapat": "Kill lasers and plates",
  "Lazerler, tarayan ışınlar ve basınç plakaları baştan devre dışı.": "Lasers, sweeping beams and pressure plates are disabled from the start.",
  "Alarm sistemine sız": "Hack the alarm system",
  "2 dakika sonra bütün güvenlik sistemi kapanır.": "After 2 minutes the whole security system shuts down.",
  "Karşı çatıda": "On the opposite roof",
  "Bekçileri haritada gösterir, yaklaşınca telsizle uyarır.": "Shows the guards on the map and radios a warning when they get close.",
  "Sokak başında": "At the corner",
  "Polisi yanlış adrese yollar: polis 25 saniye geç gelir.": "Sends the police to the wrong address: they arrive 25 seconds late.",
  "Ön cadde": "Main street",
  "Kamyon ana girişin önünde bekler.": "The truck waits in front of the main entrance.",
  "Arka sokak": "Back alley",
  "Kamyon binanın arkasında bekler; arka kapı açık olur.": "The truck waits behind the building; the back door is left open.",
  "Sahte ihbar": "Fake tip-off",
  "Bekçiler ilk 45 saniye binanın önüne çıkar.": "The guards step out front for the first 45 seconds.",
  "Yedekte bekle": "Stand by",
  "Kasa Ekipmanı": "Safe Gear",
  "Termik matkap": "Thermal drill",
  "Kasa daha kolay açılır ama her aşama gürültü yapar.": "The safe opens more easily, but every stage makes noise.",
  "Stetoskop": "Stethoscope",
  "Sessiz: kadranın tıklarını net duyarsın, yanlış dönüş daha az ses çıkarır.": "Silent: you hear the dial's clicks clearly and wrong reversals make less noise.",
  "Satış Salonu": "Showroom",
  "Mağaza Katı": "Sales Floor",
  "Ofis": "Office",
  "Güvenlik Odası": "Security Room",
  "Kasa Dairesi": "Vault",
  "Giriş Holü": "Lobby",
  "Sergi Salonu": "Exhibition Hall",
  "Vezne": "Teller",
  "Kamp Yatağı": "Cot",
  "Mücevher Vitrini": "Jewelry Display",
  "Teşhir Masası": "Display Table",
  "Kasa Bankosu": "Checkout Counter",
  "Vezne Bankosu": "Teller Counter",
  "Kiralık Kasalar": "Safe Deposit Boxes",
  "Güvenlik Masası": "Security Desk",
  "Dinozor İskeleti": "Dinosaur Skeleton",
  "Çelik Kasa Kapısı": "Steel Vault Door",
  "Altın Firavun Maskesi": "Golden Pharaoh Mask",
  "Kraliyet Tacı": "Royal Crown",
  "Antik Amfora": "Ancient Amphora",
  "Amonit Fosili": "Ammonite Fossil",
  "Hazine Bonosu": "Treasury Bond",
  "Hesap Makinesi": "Calculator",
  "Çekmece": "Drawer",
  "Şifonyer çekmecesi": "Dresser drawer",
  "Masa çekmecesi": "Desk drawer",
  "Oyuncak sandığı": "Toy chest",
  "Mutfak dolabı": "Kitchen cabinet",
  "Makyaj çekmecesi": "Vanity drawer",
  "Dresuar çekmecesi": "Console drawer",
  "TV ünitesi dolabı": "TV cabinet",
  "Tezgâh çekmecesi": "Counter drawer",
  "Bar dolabı": "Bar cabinet",
  "Üst dolap": "Wall cabinet",
  "Kiralık kasalar": "Safe deposit boxes",
  "Kasa çekmecesi": "Cash drawer",
  "Evlerle işimiz bitti Red Crime. Artık dükkân soyuyoruz. İlk durak: Altın Sarayı Kuyumcusu.": "We're done with houses, Red Crime. Now we hit stores. First stop: Golden Palace Jewelers.",
  "Kuyumcu mu? Oralar kale gibidir Reis.": "A jeweler? Those places are fortresses, Boss.",
  "Kale değil ama yakın. Vitrinlerin önünde hareket sensörleri var: ayakta yürürsen öterler. Eğilerek geç.": "Not a fortress, but close. There are motion sensors in front of the displays: walk upright and they go off. Crouch past them.",
  "Bir de yere gömülü basınç plakaları. Parlak metal bir şey görürsen üstünden atla.": "And pressure plates set into the floor. If you see something shiny and metal, jump over it.",
  "Gece bekçisi güvenlik odasında horul horul uyur. Kiralık kasalar bodrumda, çekmece çekmece altın.": "The night watchman snores away in the security room. Deposit boxes in the basement, drawer after drawer of gold.",
  "Eğilerek, atlayarak, sessizce. Anlaşıldı.": "Crouching, jumping, quietly. Got it.",
  "Tarih Müzesi. Bu gece altın maske ve kraliyet tacı sergiden sökülüyor... bizim tarafımızdan.": "The History Museum. Tonight the golden mask and the royal crown come off display... courtesy of us.",
  "Müzeler lazerle dolu olur ama...": "Museums are full of lasers, though...",
  "Hem de ne lazer. Bazıları galeriyi bir uçtan bir uca tarıyor. Işının arkasından yürü, yetişmesine izin verme.": "And what lasers. Some sweep the gallery end to end. Walk behind the beam, don't let it catch up with you.",
  "Bir bekçi devriye geziyor, bir tanesi de güvenlik odasında uyuyor. İkisine de görünme.": "One guard patrols, another sleeps in the security room. Don't let either of them see you.",
  "Tarih yazacağız Reis.": "We're going to make history, Boss.",
  "Tarih çalacağız evlat. Fark ince.": "We're going to steal history, kid. Subtle difference.",
  "TeknoPark. Şehrin en büyük elektronik mağazası. Telefonlar, dizüstüler, konsollar... Hepsi yeni, hepsi kutulu.": "TechnoPark. The city's biggest electronics store. Phones, laptops, consoles... All new, all boxed.",
  "Elektronik ağırdır ama değerlidir.": "Electronics are heavy, but they're worth it.",
  "Küçükleri çuvala, büyükleri kamyona. Müdürün kasası üst katta, deposu bodrumda.": "Small stuff in the bag, big stuff in the truck. The manager's safe is upstairs, the stockroom is in the basement.",
  "İki bekçi var bu sefer. Biri devriye, biri güvenlik odasında. Kameralar her reyonda.": "Two guards this time. One on patrol, one in the security room. Cameras on every aisle.",
  "Bu gece herkese bedava alışveriş.": "Free shopping for everyone tonight.",
  "Red Crime. Artık oyun bitti. Banka soyacağız.": "Red Crime. The games are over. We're robbing a bank.",
  "Banka mı?! Reis, bu başka lig...": "A bank?! Boss, that's a different league...",
  "O yüzden yalnız gitmiyorsun. Ekibi topladım: bir hacker, bir gözcü, bir şoför ve bir dikkat dağıtıcı. İsim yok, sadece iş.": "That's why you're not going alone. I've put a crew together: a hacker, a lookout, a driver and a decoy. No names, just the job.",
  "Planı sen yapacaksın. Nereden gireceksin, kim nerede duracak, kasayı neyle açacaksın. Her seçimin bir bedeli var.": "You make the plan. Where you go in, who stands where, what you open the vault with. Every choice has a price.",
  "Bir kere alarm çaldı mı banka kilitlenir, polis bir dakikada gelir. Yanlış hesap yapma.": "Once the alarm goes off the bank locks down and the police are there in a minute. Don't miscalculate.",
  "Planı görmek istiyorum. Her köşesini.": "I want to see the plan. Every corner of it.",
  "Red Crime... Otur şuraya. Sana hiç anlatmadım, neden köprü altında yaşadığımı.": "Red Crime... Sit down. I never told you why I live under a bridge.",
  "Yıllar önce Tefeci'ye borçlandım. Ödeyemedim. Her şeyimi aldı. Şimdi de süre verdi: bu hafta.": "Years ago I borrowed from The Loan Shark. I couldn't pay. He took everything. Now he's given me a deadline: this week.",
  "Ne kadar borç Reis?": "How much do you owe, Boss?",
  "Bir bankanın kasası kadar. O yüzden Hazine Bankası. Genel müdürlük. Şehrin kalbi.": "As much as a bank vault holds. That's why it's the Treasury Bank. Headquarters. The heart of the city.",
  "Üç bekçi, onlarca kamera, tarayan lazerler, dev bir kasa. Ekip hazır, plan senin.": "Three guards, dozens of cameras, sweeping lasers, a giant vault. The crew is ready, the plan is yours.",
  "Ve dinle beni iyi: iki hakkın var. İkisinde de olmazsa... Tefeci ikimizi de bulur. Ben de onu beklemem.": "And listen carefully: you get two tries. If both fail... The Loan Shark finds us both. And I won't wait for him.",
  "Anlıyorum Reis. İki hak.": "I understand, Boss. Two tries.",
  "Sen benim en iyi adamımsın evlat. Bunu hiç unutma. Şimdi git ve efsane ol.": "You're my best, kid. Never forget that. Now go and become a legend.",
  "Bu işten en az {v} değerinde mal çıkarman lazım. Çıkaramazsan anlaşmamız feshedilir.": "You need to get at least {v} worth of goods out of this job. If you can't, our deal is off.",
  "Bu SON hakkın Red Crime. Son. Anladın mı?": "This is your LAST chance, Red Crime. The last. Understood?",
  "Unutma: {n} hakkın var. Sonra benim sıram.": "Remember: you have {n} tries. Then it's my turn.",
  "Hmmm...": "Hmmm...",
  "İki kez... İki kez her şeyi mahvettin, Red Crime.": "Twice... Twice you ruined everything, Red Crime.",
  "Reis... Bir şans daha ver. Bu sefer olacak, yemin ederim...": "Boss... Give me one more chance. This time it'll work, I swear...",
  "Tefeci'nin adamları yolda. Borcu ödeyemedim. Sen de, ben de bittik.": "The Loan Shark's men are on their way. I couldn't pay the debt. We're both finished.",
  "Sana güvenmiştim evlat. En iyi adamım demiştim...": "I trusted you, kid. I called you my best...",
  "OYUN BİTTİ": "GAME OVER",
  "Tefeci'ye olan borç hiç ödenmedi. Tüm ilerleme silindi.": "The debt to The Loan Shark was never paid. All progress has been erased.",
  "Her şey 1. bölümden, köprü altından yeniden başlıyor.": "Everything starts over from level 1, under the bridge.",
  "Red Crime... Başardın. Tefeci'nin borcu kapandı. Artık kimseye borcumuz yok.": "Red Crime... You did it. The Loan Shark's debt is paid. We owe nobody anything now.",
  "Köprü altından Boğaz'a, Reis. Kim inanırdı?": "From under a bridge to the Bosphorus, Boss. Who'd have believed it?",
  "Ben inandım evlat. İlk günden beri. Sessiz, hızlı, temiz.": "I did, kid. From day one. Silent, fast, clean.",
  "Sessiz, hızlı, temiz.": "Silent, fast, clean.",
  "TEBRİKLER! OYUNU KAZANDIN!": "CONGRATULATIONS! YOU WON THE GAME!",
  "Red Crime ve Reis köprü altından Boğaz'daki yalıya taşındı.": "Red Crime and the Boss moved from under the bridge to a mansion on the Bosphorus.",
  "GELİŞTİRİCİ": "DEVELOPER",
  "OYUN TASARIMI · PROGRAMLAMA · GRAFİK · SES": "GAME DESIGN · PROGRAMMING · ART · SOUND",
  "BAŞROLDE": "STARRING",
  "Reis — köprünün efendisi": "The Boss — master of the bridge",
  "Oyunumuzu oynadığınız için teşekkür ederiz!": "Thank you for playing our game!",
  "ENTER: geç": "ENTER: skip",
  "Oyunumuzu bitirdiğiniz için bir sonraki oyunumuzda": "For finishing our game, you've earned on our next game",
  "%80 İNDİRİM KAZANDINIZ!": "AN 80% DISCOUNT!",
  "İndirim kodunu kaybetmeyin!": "Don't lose your discount code!",
  "Kopyalandı ✓": "Copied ✓",
  "C: kodu kopyala · ENTER: ana menü": "C: copy code · ENTER: main menu",
  "FİNALİ İZLE": "WATCH THE FINALE",
  "Polisi yanlış adrese yolladım, biraz vaktin var!": "I sent the cops to the wrong address, you've got some time!",
  "Kameralar kör! 90 saniyen var.": "Cameras are blind! You've got 90 seconds.",
  "Lazerler ve plakalar kapalı. Kameralar hâlâ açık, dikkat.": "Lasers and plates are off. Cameras are still on, careful.",
  "Alarm sistemine sızıyorum. 2 dakika dayan.": "I'm getting into the alarm system. Hold on for 2 minutes.",
  "Sahte ihbar yapıldı. Bekçiler 45 saniye dışarıda!": "Fake tip-off made. The guards are outside for 45 seconds!",
  "İçerideyim! Bütün güvenlik sistemi kapandı.": "I'm in! The whole security system is down.",
  "Dikkat! Bekçi sana doğru geliyor!": "Careful! A guard is heading your way!",
  "Dikkat! Biri yaklaşıyor, saklan!": "Careful! Someone's coming, hide!",
  "{c} açıldı: {n} eşya çıktı!": "{c} opened: {n} items fell out!",
  "Uyarı atışı! Herkes kaçışıyor... ama polis yolda!": "Warning shot! Everyone's scattering... but the police are on the way!",
  "Aç: {c}": "Open: {c}",
  "Kasam açılmış!": "My safe's been opened!",
  "Soyulmuşuz!": "We've been robbed!",
  "Silah var! Kaçın!": "He's got a gun! Run!",
  "Asılsız ihbar... Geri dönüyorum.": "False alarm... Heading back.",
  "Hareket sensörü seni algıladı!": "A motion sensor detected you!",
  "Basınç plakasına bastın!": "You stepped on a pressure plate!",
  "Tarayan lazere yakalandın!": "The sweeping laser caught you!",
  "İZ BIRAKMA": "LEAVE NO TRACE",
  "Plan masası hazır. Her şeyi bir kez daha gözden geçir.": "The planning table is ready. Go over everything one more time.",
  "Tamamdır: {o}.": "Done: {o}.",
  "SOYGUN PLANI": "HEIST PLAN",
  "KASA": "SAFE",
  "KAMYON": "TRUCK",
  "GİRİŞ": "ENTRY",
  "Sensör": "Sensor",
  "Kilitli kapı": "Locked door",
  "PLANI ONAYLA · YOLA ÇIK": "CONFIRM PLAN · MOVE OUT",
  "↑↓ seç · ←→ değiştir · ENTER onayla · ESC geri": "↑↓ select · ←→ change · ENTER confirm · ESC back",
  "SÖZLEŞME FESHEDİLDİ": "CONTRACT TERMINATED",
  "Reis: \"Hedefi tutturamadın. Bir hakkın kaldı Red Crime. SON hakkın.\"": "The Boss: \"You missed the target. You have one try left, Red Crime. Your LAST.\"",
  "Reis: \"İkinci kez... Köprü altına gel. Konuşacağız.\"": "The Boss: \"The second time... Come to the bridge. We need to talk.\"",
  "Reis: \"En az {v} demiştim. Bu işin parası yatmaz, sözleşme feshedildi.\"": "The Boss: \"I said at least {v}. This job doesn't pay, the contract is off.\"",
  "Son hakkın kaldı. Reis sabırsızlanıyor...": "One try left. The Boss is losing patience...",
  "Hiç hakkın kalmadı. Reis seni köprü altında bekliyor.": "No tries left. The Boss is waiting for you under the bridge.",
  "{c} kamera · {l} lazer · {m} sensör": "{c} cameras · {l} lasers · {m} sensors",
  "Yükleniyor...": "Loading...",
  "2/2 · MAYMUNCUK": "2/2 · LOCKPICK",
  "Sol tuşla pimin altında yukarı sürükle: yeşil çizgide oturur": "Hold left button under a pin and drag up: it sets on the green line",
  "Fazla kaldırırsan pim düşer ve ses çıkar": "Lift too far and the pin drops with a noise",
  "MAYMUNCUK": "LOCKPICK",
  "SESSİZ SIZMA": "QUIET INFILTRATION",
  "ŞÜPHE": "SUSPICION",
  "ALARM": "ALARM",
  "TAKTİK MÜDAHALE": "TACTICAL RESPONSE",
  "Durum: {s}": "Status: {s}",
  "Ortam sakinleşti. {s}": "Things have calmed down. {s}",
  "SESSİZ ALARM: güvenlik şirketi polisi aradı.": "SILENT ALARM: the security company has called the police.",
  "911 ARANDI! Kaçmak için {t} var!": "911 CALLED! You have {t} to get out!",
  "Matkap uçları bitti. Kilit kırılamadı.": "Out of drill bits. The lock held.",
  "Son matkap ucu da kırıldı!": "The last drill bit snapped!",
  "Uç aşırı ısındı ve kırıldı! Kalan uç: {n}": "The bit overheated and snapped! Bits left: {n}",
  "Pim fazla kalktı ve düştü.": "Pin overset and dropped.",
  "Kilit döndü!": "The lock turned!",
  "KİLİDİ KIR": "BREACH THE LOCK",
  "1/2 · MATKAP": "1/2 · DRILL",
  "Her ses kapıdan duyulur · ESC: vazgeç": "Every sound carries through the door · ESC: abort",
  "BASKI": "PRESSURE",
  "ISI": "HEAT",
  "UÇ": "BITS",
  "Sol tuşu basılı tut: del · Baskıyı yeşil bantta tut": "Hold left button to drill · Keep pressure in the green band",
  "Bu eşya çuvala sığmaz.": "This item won't fit in the bag.",
  "Bantlı Nakit Deste": "Strapped Cash Bundle",
  "Hamiline Yazılı Tahvil": "Bearer Bonds",
  "Sertifikalı Koleksiyon Saati": "Graded Collector's Watch",
  "Pırlanta Gerdanlık": "Diamond Necklace",
  "Derecelendirilmiş Nadir Sikke": "Graded Rare Coin",
  "Şifreli Donanım Cüzdanı": "Encrypted Hardware Wallet",
  "1 kg Külçe Altın": "1 kg Gold Bullion",
  "Sertifikalı Pırlanta Kesesi": "Certified Loose Diamonds",
  "Emekli Öğretmen": "The Retired Teacher",
  "Kasap": "The Butcher",
  "Doktor": "The Doctor",
  "Kuyumcu": "The Jeweler",
  "Holding Patronu": "The Tycoon",
  "Patronun Eşi": "The Tycoon's Wife",
  "Koleksiyoncu": "The Collector",
  "Golcü": "The Striker",
  "Milletvekili": "The MP",
  "Vekilin Eşi": "The MP's Wife",
  "Oligark": "The Oligarch",
  "Oligarkın Eşi": "The Oligarch's Wife",
  "Emekli Paşa": "The Retired General",
  "Paşanın Eşi": "The General's Wife",
  "Gece Bekçisi": "The Night Watchman",
  "Kıdemli Bekçi": "The Senior Watchman",
  "Özel Güvenlik": "The Security Guard",
  "Vardiya Amiri": "The Shift Supervisor",
  "Bekçi Köpeği": "The Guard Dog",
  "Hacker": "The Hacker",
  "Gözcü": "The Lookout",
  "Şoför": "The Driver",
  "Dikkat Dağıtıcı": "The Decoy",
  "Sıradan": "Common",
  "Nadir": "Rare",
  "Epik": "Epic",
  "Efsanevi": "Legendary",
  "Kolay": "Easy",
  "Normal": "Normal",
  "Zor": "Hard",
  "Düşük": "Low",
  "Orta": "Medium",
  "Yüksek": "High",
  "AÇIK": "ON",
  "KAPALI": "OFF",
  "Emekli Öğretmenin Evi": "The Retired Teacher's House",
  "Küçük İki Katlı Ev": "Small Two-Story House",
  "Mahallenin sessiz köşesinde iki katlı, sevimli bir ev. Emekli Öğretmen üst kattaki yatak odasında, kapısı kapalı uyur.": "A cute two-story house on a quiet corner of the neighborhood. The Retired Teacher sleeps upstairs in a bedroom with the door closed.",
  "Kasabın Evi": "The Butcher's House",
  "Eski İki Katlı Ev": "Old Two-Story House",
  "Kasap dükkânın hasılatını eve getirir. Yatak odasının kapısını hep kilitler; eski evin merdivenleri ve döşemesi gıcırdar.": "The Butcher brings the shop's takings home every night. He always locks his bedroom door, and the old stairs and floorboards creak.",
  "Doktorun Dubleksi": "The Doctor's Duplex",
  "Dubleks + Bodrum": "Duplex + Basement",
  "Modern bir dubleks ve gizemli bir bodrum. Doktor kuş uykusu uyur; çalışma odası ve bodrum kilitlidir.": "A modern duplex with a mysterious basement. The Doctor is a very light sleeper; the study and basement are locked.",
  "Kuyumcunun Evi": "The Jeweler's House",
  "İki Kat + Bodrum · Kameralar": "Two Floors + Basement · Cameras",
  "Kapalıçarşı'nın en zengin kuyumcusu. Evinde ilk kez güvenlik kameraları ve bir alarm sistemi var. Kamera seni görürse alarm çalar!": "The richest jeweler of the Grand Bazaar. His house has security cameras and an alarm system for the first time. If a camera sees you, the alarm goes off!",
  "Holding Patronunun Rezidansı": "The Tycoon's Residence",
  "Dört Katlı Rezidans": "Four-Story Residence",
  "Dört kat, iki sakin, kameralar ve ilk lazer alarmı. Holding Patronu ve eşi ayrı katlarda, kilitli odalarda uyur.": "Four floors, two residents, cameras and the first laser alarm. The Tycoon and his wife sleep on separate floors, in locked rooms.",
  "Koleksiyoncunun Galeri Villası": "The Collector's Gallery Villa",
  "Üç Katlı Sanat Villası": "Three-Story Art Villa",
  "Ünlü bir sanat koleksiyoncusunun villası bir müze gibi: duvarlarda başyapıtlar, koridorlarda lazerler, köşelerde kameralar.": "A famous art collector's villa is like a museum: masterpieces on the walls, lasers in the halls, cameras in the corners.",
  "Yıldız Futbolcunun Malikânesi": "The Star Striker's Mansion",
  "Havuzlu Malikâne + Köpek": "Mansion with Pool + Dog",
  "Süper Lig'in yıldız golcüsünün malikânesi. Havuz, oyun odası, kupa dolapları... ve bahçede bir bekçi köpeği.": "The mansion of the league's star striker. A pool, a game room, trophy cabinets... and a guard dog in the garden.",
  "Milletvekilinin Boğaz Yalısı": "The MP's Bosphorus Mansion",
  "Yalı + Özel Güvenlik": "Waterfront Mansion + Private Security",
  "Boğaz kıyısında tarihi bir yalı. Artık bir özel güvenlik görevlisi de var: uyumaz, el feneriyle devriye gezer.": "A historic waterfront mansion on the Bosphorus. Now there is a private security guard too: he never sleeps and patrols with a flashlight.",
  "Oligarkın Köşkü": "The Oligarch's Manor",
  "Beş Katlı Kale": "Five-Story Fortress",
  "Yurt dışından gelen gizemli bir milyarderin köşkü. İki güvenlik görevlisi, yanıp sönen lazerler ve her köşede kamera. Hata affetmez.": "The manor of a mysterious foreign billionaire. Two security guards, blinking lasers and cameras in every corner. No room for mistakes.",
  "Paşa Konağı": "The General's Mansion",
  "Dev Bahçeli Konak · Final": "Giant Garden Mansion · Finale",
  "Devasa bir bahçe, havuz, kulübe, iz süren zeki bir Doberman, iki bekçi, hazine odası ve şehrin en gelişmiş güvenlik sistemi. Büyük final!": "A huge garden, a pool, a shed, a clever tracking Doberman, two guards, a treasure room and the most advanced security system in town. The grand finale!",
  "Hanımefendi": "The Lady",
  "Polis": "The police",
  "Elektronik Maymuncuk": "Electronic Lockpick",
  "Kilitli bir kapıyı saniyeler içinde, sessizce açar.": "Silently opens a locked door in seconds.",
  "Kamera Karıştırıcı": "Camera Jammer",
  "Evdeki tüm kameraları 25 saniye boyunca kör eder.": "Blinds every camera in the house for 25 seconds.",
  "Uyku Gazı Bombası": "Sleeping Gas Grenade",
  "Yakınındaki uyanık herkesi (köpek dahil) 25 saniye uyutur.": "Puts everyone awake nearby (dogs included) to sleep for 25 seconds.",
  "Sis Bombası": "Smoke Bomb",
  "Kalın bir duman bulutu: içindeyken kimse seni göremez.": "A thick cloud of smoke: nobody can see you inside it.",
  "EMP Cihazı": "EMP Device",
  "Alarm sistemini, kameraları ve lazerleri tamamen devre dışı bırakır.": "Completely shuts down the alarm system, cameras and lasers.",
  "Gece Görüş Gözlüğü": "Night Vision Goggles",
  "Kalıcı. El feneri olmadan da karanlıkta çok daha geniş görürsün.": "Permanent. See much further in the dark, even without a flashlight.",
  "Termal Tarayıcı": "Thermal Scanner",
  "Kalıcı. Duvarların ardındaki herkesi ve kasa anahtarını haritada gösterir.": "Permanent. Shows everyone behind walls and the safe key's location.",
  "Şoföre Rüşvet": "Bribe the Driver",
  "Kalıcı. Şoför her soygunda 45 saniye fazla bekler.": "Permanent. The Driver waits 45 extra seconds on every heist.",
  "Kedi Pati Ayakkabı": "Cat-Paw Shoes",
  "Ayak seslerini azaltır.": "Reduces your footstep noise.",
  "-%{v} ayak sesi": "-{v}% footstep noise",
  "Taktik El Feneri": "Tactical Flashlight",
  "Daha uzun ve geniş ışık huzmesi.": "A longer and wider light beam.",
  "+%{v} menzil": "+{v}% range",
  "Büyük Çuval": "Big Sack",
  "Cebe atılabilen küçük eşya kapasitesi.": "More room for small pocketable items.",
  "{v} küçük eşya": "{v} small items",
  "Protein Tozu": "Protein Powder",
  "Ağır eşyalar seni daha az yavaşlatır.": "Heavy items slow you down less.",
  "-%{v} ağırlık cezası": "-{v}% weight penalty",
  "Kasa Ustası Kursu": "Safecracking Course",
  "Kasa kadranında ve kilit delmede daha geniş hata payı.": "More margin for error on safe dials and lock drilling.",
  "+%{v} hedef bölge": "+{v}% target zone",
  "Maraton Ciğeri": "Marathon Lungs",
  "Koşarken daha hızlısın.": "You run faster.",
  "+%{v} koşu hızı": "+{v}% run speed",
  "Salon": "Living Room",
  "Mutfak": "Kitchen",
  "Yemek Odası": "Dining Room",
  "Yatak Odası": "Bedroom",
  "Ebeveyn Yatak Odası": "Master Bedroom",
  "Çocuk Odası": "Kids' Room",
  "Çalışma Odası": "Study",
  "Kütüphane": "Library",
  "Banyo": "Bathroom",
  "Hol": "Hallway",
  "Depo": "Storage",
  "Şarap Mahzeni": "Wine Cellar",
  "Atölye": "Workshop",
  "Oyun Odası": "Game Room",
  "Hazine Odası": "Treasure Room",
  "Giyinme Odası": "Dressing Room",
  "Müzik Odası": "Music Room",
  "Galeri": "Gallery",
  "Kupa Odası": "Trophy Room",
  "Spor Salonu": "Home Gym",
  "Bahçe": "Garden",
  "Ooo, Red Crime! Gel bakalım evlat. Soğuk mu? Şu varilin başına geç, ısın biraz.": "Well, well, Red Crime! Come here, kid. Cold out? Step up to the barrel and warm yourself.",
  "Reis... Aradığını duydum. İş varmış.": "Boss... I heard you were looking for me. Something about a job.",
  "İş var, hem de senin ilk işin. Mahallenin ucunda emekli bir öğretmen yaşıyor. İsim yok, sadece hedef: Emekli Öğretmen.": "There\'s a job, and it\'s your first. A retired teacher lives at the end of the block. No names, just a target: The Retired Teacher.",
  "Adam her gece dokuzda yatar. Yatak odası üst katta, kapısını kapatıp öyle uyur. Horultusunu sokaktan duyarsın.": "He goes to bed at nine every night. His bedroom is upstairs and he sleeps with the door shut. You can hear him snoring from the street.",
  "Evde ne var ki? Bir öğretmenden ne çıkar?": "What's in the house? What could a teacher have?",
  "Kırk yıl biriktirmiş evlat. Karısından kalma bilezikler, eski sikkeler, duvarda tablolar...": "Forty years of savings, kid. His late wife's bracelets, old coins, paintings on the walls...",
  "Bir de küçük bir kasası varmış. Anahtarını evde bir yerde saklıyor, bankaya güvenmez.": "He has a small safe too. He hides the key somewhere in the house; he doesn't trust banks.",
  "Ya uyanırsa?": "What if he wakes up?",
  "Uyanırsa ışıkları yakar, bütün evi oda oda arar, polisi arar. O yüzden uyanmayacak.": "If he wakes up he'll turn on the lights, search the house room by room and call the cops. So he won't wake up.",
  "Kamyonu kapının önüne çektirdim. Şoför süre dolana kadar bekler, sonra gazlar. Kimseyi beklemez.": "I had the truck parked by the door. The Driver waits until the clock runs out, then he floors it. He waits for nobody.",
  "Beş dakika yeter. Sessiz, hızlı, temiz.": "Five minutes is enough. Quiet, quick, clean.",
  "İşte benim çocuğum! Hadi bakalım, yolun açık olsun.": "That's my boy! Off you go, good luck.",
  "Emekli Öğretmen hâlâ bileziklerini arıyormuş, hah! İyi iş çıkardın Red Crime.": "They say The Retired Teacher is still looking for his bracelets, hah! Nice work, Red Crime.",
  "Sıradaki: Kasap. Dükkânın hasılatını her akşam eve götürüyor, bankaya uğramıyor.": "Next up: The Butcher. He takes the shop's takings home every evening and never goes near a bank.",
  "Evi nasıl bir yer?": "What's the house like?",
  "İki katlı eski bir ev. Kasap yatak odasının kapısını kilitler. Al şu matkabı ve maymuncuğu, kilit senin işin artık.": "An old two-story house. The Butcher locks his bedroom door. Take this drill and pick set, locks are your job now.",
  "Bu gece yağmur da yağıyor. Çatıdaki tıkırtıda seni kimse duymaz... pek.": "It's raining tonight too. With the rain on the roof nobody will hear you... mostly.",
  "Yağmurlu gece, dolu kasa. Gidiyorum Reis.": "Rainy night, full safe. I'm on it, Boss.",
  "Bu seferki farklı. Doktor. Yıllarca nöbet tutmuş, kuş uykusu uyur.": "This one's different. The Doctor. Years of night shifts; sleeps like a bird.",
  "Dubleks bir ev, altında da bodrum var. Bodruma salondaki kapaktan el merdiveniyle iniliyor.": "A duplex with a basement underneath. You get down there by a ladder through a hatch in the floor.",
  "Bodrumda ne var?": "What's in the basement?",
  "Şarap mahzeni, alet edevat... Söylentiye göre pahalı tıbbi cihazlar da orada. Kapıların çoğu kilitli, maymuncuğunu hazır tut.": "A wine cellar, tools... and rumor says expensive medical equipment. Most doors are locked, keep your lockpick ready.",
  "Kadının telefonu hep yanında. Seni görürse saniyesinde polisi arar, hesabını ona göre yap.": "Her phone is always by her side. If she sees you she'll call the police in a second. Plan accordingly.",
  "Bir de sis var... Tam bizim hava.": "And there's fog... Perfect weather for us.",
  "Kuyumcu. Kapalıçarşı'nın en zengin adamı. Dükkânı değil, evini soyacağız.": "The Jeweler. The richest man in the Grand Bazaar. We're hitting his house, not his shop.",
  "Kuyumcunun evi... Kolay olmaz bu.": "A jeweler's house... That won't be easy.",
  "Olmaz tabii. Adam geçen ay kamera taktırmış. Kameralar döner durur, önüne çıkarsan alarm öter.": "Of course not. He had cameras installed last month. They keep sweeping; step in front of one and the alarm goes off.",
  "Ama kapının yanında bir alarm paneli var. Kablolarını çözersen bütün sistem susar.": "But there's an alarm panel by the door. Crack its wiring and the whole system goes quiet.",
  "Alarm bir kere çaldı mı herkes uyanır, polis de yoldadır. Aklında olsun.": "Once that alarm rings, everybody wakes up and the police are on their way. Remember that.",
  "Kameraların arkasından dolaşırım Reis.": "I'll sneak behind the cameras, Boss.",
  "Bu arada, kazandığın parayla internetin karanlık köşelerinden güzel oyuncaklar alabilirsin. Benden duymadın.": "By the way, you can buy nice toys from the dark corners of the internet with your money. You didn't hear it from me.",
  "Büyük balık zamanı Red Crime. Holding Patronu ve eşi.": "Time for the big fish, Red Crime. The Tycoon and his wife.",
  "Dört katlı bir rezidans. Kavgalılarmış, ayrı katlarda, kilitli odalarda yatıyorlar. Biri kalkarsa öteki de kalkar.": "A four-story residence. They're feuding, so they sleep on separate floors in locked rooms. If one wakes, the other does too.",
  "Dört kat... Aşağı taşıması uzun sürer.": "Four floors... Carrying stuff down will take forever.",
  "O yüzden gözün değerli olanda olsun. Saat, mücevher, nakit. Koltuk takımıyla uğraşma.": "So keep your eye on the valuable stuff. Watches, jewelry, cash. Don't bother with the sofa.",
  "Kameralar var, bir de koridorlardan birinde lazer ışınları. Kırmızı çizgiye değme, zıpla ya da eğil.": "There are cameras, and laser beams in one of the halls. Don't touch the red line, jump over it or duck under it.",
  "Patronun kasası bu şehrin yarısından zengin diyorlar. Anahtarı evde bir yerde olmalı.": "They say The Tycoon's safe is richer than half this city. The key must be somewhere in the house.",
  "Koleksiyoncu. Adını bilmene gerek yok. Villası küçük bir müze gibi.": "The Collector. You don't need a name. The villa is like a little museum.",
  "Tablo mu çalacağız? Onları kim alır?": "We're stealing paintings? Who buys those?",
  "Alan çok evlat, alan çok. Bir tanesi bizim köprüyü on kere satın alır.": "Plenty of buyers, kid, plenty. One of them could buy our bridge ten times over.",
  "Lazerler bu evde yanıp sönüyor. Söndüğü anı kolla, geç. Kameralar her galeride.": "The lasers in this house blink. Wait for them to turn off, then go. There are cameras in every gallery.",
  "Koleksiyoncu uykusunda bile koleksiyonunu düşünür. Bir tablo yere düşerse fırlar yataktan.": "The Collector thinks about the collection even in her sleep. If a painting hits the floor, expect a leap out of bed.",
  "Eldivenlerimi giydim bile.": "I've already got my gloves on.",
  "Golcü! Geçen hafta üç gol attı, bu hafta biz atacağız.": "The Striker! He scored three goals last week; this week it's our turn to score.",
  "Malikânenin koca bir bahçesi, havuzu var. Bahçede de bir bekçi köpeği dolaşıyor.": "The mansion has a big garden and a pool. And a guard dog roams the garden.",
  "Köpek... Havlarsa ne olacak?": "A dog... What if it barks?",
  "Havlarsa ev uyanır. Isırırsa elindekini düşürürsün. Çalıların arkasından git, havuzdan uzak dur.": "If it barks, the house wakes up. If it bites, you'll drop what you're holding. Stay behind the bushes and away from the pool.",
  "İçeride kupa dolapları, imzalı formalar, oyun konsolları... Golcü eşyalarına çok düşkün, kasası da bodrumda.": "Inside: trophy cabinets, signed jerseys, game consoles... The Striker loves his stuff, and his safe is in the basement.",
  "Hazırım Reis. Top ayağımda.": "I'm ready, Boss. The ball's at my feet.",
  "Boğaz'da bir yalı. Sahibi milletvekili, eşiyle birlikte orada kalıyor.": "A waterfront mansion on the Bosphorus. The owner is a member of parliament who lives there with his wife.",
  "Dikkat et: yalının bir özel güvenlik görevlisi var. Uyumaz, el feneriyle bütün gece devriye gezer.": "Careful: the mansion has a private security guard. He doesn't sleep; he patrols all night with a flashlight.",
  "Uyumayan biri... Onu nasıl atlatacağım?": "Someone who never sleeps... How do I get past him?",
  "Ritmini öğren. Nereden geçtiğini izle, arkasından dolaş. Görürse kovalar, yakalarsa oyun biter.": "Learn his rhythm. Watch his route and slip behind him. If he sees you he'll chase you; if he catches you, it's over.",
  "Karanlık ağdan aldığın oyuncakları bu gece kullan. Sis bombası, uyku gazı... ne varsa.": "Use the toys you bought on the dark web tonight. Smoke bombs, sleeping gas... whatever you've got.",
  "Gölge gibi girip çıkacağım.": "I'll slip in and out like a shadow.",
  "Bu iş... büyük iş. Yurt dışından gelen bir milyarder: Oligark. Şehrin tepesindeki köşkte oturuyor.": "This job... is a big one. A billionaire from abroad: The Oligarch. He lives in the manor on top of the hill.",
  "İki güvenlikçi, her köşede kamera, yanıp sönen lazerler. Kasası da bodrumdaki hazine odasında.": "Two guards, cameras in every corner, blinking lasers. His safe is in the treasure room in the basement.",
  "Reis, bu intihar gibi...": "Boss, this sounds like suicide...",
  "Değil. Alarm panelini hallet, güvenlikçilerin rotasını öğren, kilitleri sessizce aç. Adım adım.": "It's not. Deal with the alarm panel, learn the guards' routes, pick the locks quietly. Step by step.",
  "Bu işten sonra adın efsane olur Red Crime. Ya da hapiste yatarsın. İkisi de şöhret.": "After this job you'll be a legend, Red Crime. Or you'll be in jail. Either way, you're famous.",
  "Efsane olanı seçiyorum.": "I'll take the legend option.",
  "Ve... büyük final. Paşa Konağı.": "And... the grand finale. The General's Mansion.",
  "Koca bir bahçe, havuz, bahçe kulübesi. Üç kat artı bodrum. Bodrumda da hazine odası.": "A huge garden, a pool, a garden shed. Three floors plus a basement. And a treasure room down there.",
  "Bahçede bir şey havlıyor gibi...": "Something in the garden is barking...",
  "Emekli Paşa ve eşi üst katlarda, kilitli odalarda yatıyor. Hizmetçiler bu gece izinli.": "The Retired General and his wife sleep upstairs in locked rooms. The servants have the night off.",
  "Bu işi de bitirirsen köprü altından yalıya taşınıyoruz evlat. Son kez: sessiz, hızlı, temiz!": "Pull this one off and we move from under the bridge to a mansion, kid. One last time: quiet, quick, clean!",
  "Sessiz, hızlı, temiz!": "Quiet, quick, clean!",
  "Hıı...?": "Hmm...?",
  "Mmm...": "Mmm...",
  "Ne o...": "What's that...",
  "*horr*... hm?": "*snore*... hm?",
  "Kedi mi o...": "Is that the cat...",
  "Kim var orada?!": "Who's there?!",
  "Bu ses de ne?!": "What was that noise?!",
  "Hırsız mı var?!": "Is there a burglar?!",
  "Kalk bakalım...": "Up we get...",
  "Ne oluyor?!": "What's going on?!",
  "Buradan geldi...": "It came from here...",
  "Biri mi var?": "Is someone there?",
  "Hmm...": "Hmm...",
  "Kim o?": "Who is it?",
  "Çıkın ortaya!": "Come out!",
  "Neredesin?": "Where are you?",
  "Saklanma!": "Stop hiding!",
  "Bir yerlerdesin...": "You're here somewhere...",
  "Buldum seni... ya da?": "Found you... or not?",
  "HIRSIZ!": "THIEF!",
  "Dur orada!": "Stop right there!",
  "Yakaladım seni!": "Gotcha!",
  "Polis! Polis!": "Police! Police!",
  "Gel buraya!": "Get over here!",
  "Herhalde rüzgârdı...": "Must have been the wind...",
  "Kedi olmalı...": "Must be the cat...",
  "Yaşlandım galiba...": "I must be getting old...",
  "Rüya gördüm herhalde...": "I must have been dreaming...",
  "Yine uyuyamayacağım...": "Now I won't be able to sleep...",
  "Vazom!": "My vase!",
  "O antikaydı!": "That was an antique!",
  "Eyvah!": "Oh no!",
  "Ne kırıldı?!": "What broke?!",
  "Alo, polis?!": "Hello, police?!",
  "Evde hırsız var!": "There's a burglar in my house!",
  "155! Hemen gelin!": "911! Come quick!",
  "Kaçtı!": "He got away!",
  "Nereye gitti?": "Where did he go?",
  "Kayboldu...": "He's gone...",
  "Bütün evi arayacağım!": "I'll search the whole house!",
  "Bir yerlerde saklanıyorsun...": "You're hiding somewhere...",
  "Oda oda bakacağım!": "I'll check every room!",
  "Çık ortaya!": "Show yourself!",
  "Bu kapı neden açık?": "Why is this door open?",
  "Kapıyı kim açtı?": "Who opened this door?",
  "Devriye normal.": "Patrol normal.",
  "Burada bir şey yok.": "Nothing here.",
  "Hmm... sessiz gece.": "Hmm... quiet night.",
  "Merkez, her şey yolunda.": "Base, all clear.",
  "ALARM!": "ALARM!",
  "Biri içeride!": "Someone's inside!",
  "Güvenlik ihlali!": "Security breach!",
  "Başım... dönüyor...": "My head... is spinning...",
  "Çok... uykum...": "So... sleepy...",
  "Işık mı var...?": "Is that a light...?",
  "Ne oldu bana...?": "What happened to me...?",
  "YAKALADIM SENİ!": "GOTCHA!",
  "Çömelerek yürürsen neredeyse hiç ses çıkarmazsın.": "Walking crouched makes almost no noise.",
  "Küçük eşyalar çuvala girer; çuval dolunca kamyona boşalt.": "Small items go into your sack; empty it into the truck when it's full.",
  "Epik ve efsanevi eşyalar hafifçe parlar.": "Epic and legendary items glint softly.",
  "Ev sahibi uyanınca ışıkları açar. Karanlıkta saklanmak çok daha kolay.": "When the owner wakes up they turn on the lights. Hiding is much easier in the dark.",
  "Bir eşyayı Q ile fırlatıp ev sahibini başka yere yönlendirebilirsin.": "Throw an item with Q to lure the owner somewhere else.",
  "Kırılabilir eşyaları düşürme: vazo, kadeh, ayna...": "Don't drop fragile items: vases, glasses, mirrors...",
  "Açık renkli tahtalar gıcırdar. Üstlerinde çömel.": "Light-colored floorboards creak. Crouch over them.",
  "Kasa anahtarı genelde başka bir odadadır.": "The safe key is usually in a different room.",
  "SHIFT ile koşarsın ama koşmak çok ses çıkarır.": "SHIFT lets you run, but running is very loud.",
  "F ile el fenerini açıp kapatabilirsin; karanlıkta kapalı fener seni daha zor fark ettirir.": "Toggle the flashlight with F; with it off you're much harder to spot in the dark.",
  "Polis çağrılırsa süre azalır. Kamyona koş!": "If the police are called, your time drops. Run to the truck!",
  "Uyuyan birinin yüzüne el feneri tutma.": "Don't shine your flashlight in a sleeping person's face.",
  "Ağır eşyalar seni yavaşlatır ve daha sesli yürürsün.": "Heavy items slow you down and make your steps louder.",
  "M tuşu ile evin haritasını açabilirsin.": "Hold M to open the house map.",
  "İpucu: {h}": "Tip: {h}",
  "Şapırtı! Havuza düştün!": "Splash! You fell into the pool!",
  "Kamyona yüklenecek bir şey yok.": "Nothing to load into the truck.",
  "Kasa kilitli! Önce anahtarı bul.": "The safe is locked! Find the key first.",
  "Kaçmak için tekrar E bas! (Kamyondaki ganimetle)": "Press E again to escape! (with the loot in the truck)",
  "Kasa anahtarını buldun! 🔑": "You found the safe key! 🔑",
  "Çuval dolu! Kamyona boşalt.": "Sack full! Empty it into the truck.",
  "Köpek ısırdı! Elindekini düşürdün!": "The dog bit you! You dropped what you were holding!",
  "Elindeki eşya çok büyük, saklanamazsın!": "What you're holding is too big to hide with!",
  "{n} uyandı! Işıklar yandı!": "{n} woke up! The lights are on!",
  "{n} de uyandı!": "{n} woke up too!",
  "POLİS ARANDI! Hemen kaç!": "POLICE CALLED! Get out now!",
  "{n} kırıldı! (-{v})": "{n} broke! (-{v})",
  "Saklandın! Hareket etmezsen seni göremezler.": "You're hidden! Stay still and they can't see you.",
  "★ Hedefe ulaştın! Kaçabilirsin — ya da devam!": "★ Target reached! You can escape — or keep going!",
  "★★ Harika vurgun!": "★★ Great haul!",
  "★★★ EFSANE VURGUN!": "★★★ LEGENDARY HAUL!",
  "KASA AÇILDI! İçindekileri topla!": "SAFE OPEN! Grab what's inside!",
  "Alarm çalıyor, panel kilitlendi!": "The alarm is ringing, the panel is locked!",
  "Kapının önünden çekil.": "Step out of the doorway.",
  "Kilit açıldı!": "Lock picked!",
  "Panel hatalı şifreyle kilitlendi!": "Panel locked by wrong codes!",
  "Bu ekipmandan kalmadı: {n}": "You're out of: {n}",
  "Yakında kilitli bir kapı yok.": "No locked door nearby.",
  "Elektronik maymuncuk kilidi açtı.": "The electronic lockpick opened the lock.",
  "Karıştırılacak kamera yok.": "No cameras to jam.",
  "Kameralar 25 saniye kör!": "Cameras blinded for 25 seconds!",
  "Uyku gazı yayıldı!": "Sleeping gas released!",
  "Sis bombası! Görünmezsin.": "Smoke bomb! You're invisible.",
  "Bu evde kapatılacak sistem yok.": "There's no system to shut down in this house.",
  "Süre doldu! Kamyon sensiz gitti!": "Time's up! The truck left without you!",
  "Süre doldu! Kamyon kalkıyor!": "Time's up! The truck is leaving!",
  "Kaçıyoruz!": "We're out of here!",
  "Son 30 saniye!": "Last 30 seconds!",
  "Işıklar söndü. Yeniden sessizlik...": "Lights out. Silence again...",
  "Kamyona yükle (+{v})": "Load into truck (+{v})",
  "Çuvalı boşalt (+{v})": "Empty sack (+{v})",
  "Anahtarı al": "Take the key",
  "Çuvala at: {n}": "Bag it: {n}",
  "Tut: {n}": "Pick up: {n}",
  "Fırlat (dikkat dağıt)": "Throw (distraction)",
  "Sessizce yere koy": "Put down quietly",
  "Sessizce koy (ayakta: düşürür!)": "Put down quietly (standing: drops it!)",
  "Kasayı aç": "Open the safe",
  "Kasa kilitli — anahtarı bul": "Safe locked — find the key",
  "Onayla: KAÇ!": "Confirm: ESCAPE!",
  "Kaç (soygunu bitir)": "Escape (end heist)",
  "Merdivenden in": "Go downstairs",
  "Merdivenden çık": "Go upstairs",
  "El merdiveni": "Ladder",
  "DEVAM ET": "RESUME",
  "YENİDEN BAŞLA": "RESTART",
  "ANA MENÜ": "MAIN MENU",
  "KASA  [E]": "SAFE  [E]",
  "KASA  🔒": "SAFE  🔒",
  "BÖLÜM {n}": "LEVEL {n}",
  "{t} — Ev sahibini uyandırmadan en çok ganimeti kamyona yükle!": "{t} — Load the most loot into the truck without waking the owner!",
  "KASAYI AÇ": "CRACK THE SAFE",
  "KASA ANAHTARI": "SAFE KEY",
  "YAKALANDIN!": "BUSTED!",
  "DURAKLATILDI": "PAUSED",
  "Kamera seni gördü!": "A camera saw you!",
  "Lazer ışınına değdin!": "You touched a laser beam!",
  "ALARM ÇALIYOR!": "ALARM!",
  "Siren sustu... ama polis hâlâ yolda!": "The siren stopped... but the police are still coming!",
  "Güvenlik sistemi devre dışı!": "Security system disabled!",
  "SAKLANIYORSUN": "HIDDEN",
  "KAMYONDA": "IN THE TRUCK",
  "Hedef {v}": "Target {v}",
  "+ {v} üzerinde": "+ {v} on you",
  "POLİS: {t}": "POLICE: {t}",
  "Uyuyor": "Asleep",
  "UYANDI!": "AWAKE!",
  "Araştırıyor": "Investigating",
  "Arıyor": "Searching",
  "KOVALIYOR!": "CHASING!",
  "Yatağa dönüyor": "Going back to bed",
  "EVİ ARIYOR!": "SEARCHING THE HOUSE!",
  "Devriyede": "On patrol",
  "Baygın": "Knocked out",
  "{n} uyuyor": "{n} is asleep",
  "{n} HAVLIYOR!": "{n} IS BARKING!",
  "{n} tetikte": "{n} is alert",
  "Kameralar kör: {s} sn": "Cameras blind: {s}s",
  "Güvenlik kapalı": "Security off",
  "Güvenlik aktif": "Security active",
  "{c} kamera · {l} lazer": "{c} cameras · {l} lasers",
  "ÇUVAL {a}/{b}": "SACK {a}/{b}",
  "Kırılır": "Fragile",
  "HARİTA": "MAP",
  "Sen": "You",
  "Uyuyan": "Asleep",
  "Uyanık": "Awake",
  "Kovalıyor": "Chasing",
  "Kamyon / Kasa": "Truck / Safe",
  "KİLİDİ AÇ": "PICK THE LOCK",
  "Sarı pim yeşil çizgiye değdiğinde SPACE bas": "Press SPACE when the yellow pin touches the green line",
  "Hatalı deneme tıkırtı yapar · ESC: vazgeç": "Wrong attempts rattle the lock · ESC: cancel",
  "> ALARM PANELİ // BYPASS": "> ALARM PANEL // BYPASS",
  "Tur {r}/{n}   Hata {f}/{m}": "Round {r}/{n}   Errors {f}/{m}",
  "Diziyi ezberle...": "Memorize the sequence...",
  "Diziyi yön tuşlarıyla (W A S D / oklar) gir": "Enter the sequence with the direction keys (W A S D / arrows)",
  "ERİŞİM SAĞLANDI": "ACCESS GRANTED",
  "ERİŞİM REDDEDİLDİ": "ACCESS DENIED",
  "3 hatada alarm çalar · ESC: vazgeç": "3 errors trigger the alarm · ESC: cancel",
  "Sola ve sağa yürü.": "Walk left and right.",
  "SHIFT basılı tutarak koş. Koşmak hızlıdır ama ÇOK gürültü yapar!": "Hold SHIFT to run. Running is fast but VERY loud!",
  "Zıpla. Rafların ve mobilyaların üstüne böyle çıkarsın.": "Jump. This is how you get onto shelves and furniture.",
  "Çömelerek yürü. Çömelirken neredeyse hiç ses çıkarmazsın.": "Walk while crouching. You make almost no noise crouched.",
  "El fenerini kapat, sonra tekrar aç.": "Turn your flashlight off, then on again.",
  "Eve gir ve bir eşyanın yanında SPACE ile al. Küçük eşyalar çuvala girer.": "Go inside and press SPACE next to an item to take it. Small items go into your sack.",
  "Ganimeti kamyonun arkasına götür ve SPACE ile yükle. Sadece kamyondakiler sayılır.": "Take the loot to the back of the truck and press SPACE to load it. Only loot in the truck counts.",
  "Kapalı bir kapının önünde E'ye basarak aç. Kilitliyse maymuncukla açarsın.": "Press E in front of a closed door to open it. If it's locked, you'll pick it.",
  "Saklan: perde ya da dolap önünde hareketsiz dur, kanepe ya da yatak arkasında çömel.": "Hide: stand still in front of a curtain or wardrobe, or crouch behind a sofa or bed.",
  "HAZIRSIN!": "YOU'RE READY!",
  "Emekli Öğretmen üst kattaki yatak odasında uyuyor. Kasa anahtarını bul,": "The Retired Teacher is asleep upstairs. Find the safe key,",
  "ganimeti kamyona yükle ve süre bitmeden E ile kaç.": "load the loot into the truck and escape with E before time runs out.",
  "ÖĞRETİCİ {a}/{b}": "TUTORIAL {a}/{b}",
  "ENTER: öğreticiyi atla": "ENTER: skip tutorial",
  "RED CRIME": "RED CRIME",
  "Başlamak için tıkla ya da bir tuşa bas": "Click or press any key to start",
  "🎧 Kulaklıkla oynaman önerilir": "🎧 Headphones recommended",
  "Bir gece... şehrin en sessiz hırsızı işbaşında.": "One night... the city's quietest thief is at work.",
  "SESSİZ  ·  HIZLI  ·  TEMİZ": "QUIET  ·  QUICK  ·  CLEAN",
  "Devam etmek için bir tuşa bas": "Press any key to continue",
  "Geç: herhangi bir tuş": "Skip: any key",
  "SOYGUNA BAŞLA": "START HEIST",
  "GERİ": "BACK",
  "DÜKKÂN": "SHOP",
  "KARANLIK AĞ": "DARK WEB",
  "HEDEF SEÇ": "CHOOSE A TARGET",
  "Önceki bölümü tamamla": "Complete the previous level",
  "{n} kat": "{n} floors",
  " + bodrum": " + basement",
  " + dev bahçe": " + huge garden",
  " + köpek": " + dog",
  "Hedef: {v}": "Target: {v}",
  "Rekor: {v}": "Record: {v}",
  "←→ bölüm · ↑↓ düğme · ENTER onayla · ESC geri": "←→ level · ↑↓ button · ENTER confirm · ESC back",
  "Şu an: {e}": "Now: {e}",
  "Henüz yok": "Not owned yet",
  "Sonraki: {e}": "Next: {e}",
  "MAKSİMUM": "MAXED",
  "KARABORSA DÜKKÂNI": "BLACK MARKET SHOP",
  "Reis'in tedarikçisinin tezgâhı. \"Sorma nereden buldum.\"": "The Boss's supplier's stall. \"Don't ask where I got it.\"",
  "OYUNA BAŞLA": "START GAME",
  "AYARLAR": "SETTINGS",
  "NASIL OYNANIR": "HOW TO PLAY",
  "DİL: TÜRKÇE": "DİL: TÜRKÇE",
  "↑↓ seç · ENTER onayla": "↑↓ select · ENTER confirm",
  "Ana Ses": "Master Volume",
  "Müzik": "Music",
  "Efektler": "Effects",
  "Zorluk": "Difficulty",
  "İpuçları": "Tips",
  "Öğretici": "Tutorial",
  "Grafik": "Graphics",
  "Ekran Sarsıntısı": "Screen Shake",
  "Fareyle Nişan": "Mouse Aim",
  "Ses Halkaları": "Noise Rings",
  "FPS Göster": "Show FPS",
  "TAM EKRAN": "FULLSCREEN",
  "İLERLEMEYİ SIFIRLA": "RESET PROGRESS",
  "SIFIRLANDI ✓": "RESET ✓",
  "EMİN MİSİN? TEKRAR BAS": "SURE? PRESS AGAIN",
  "Açılışı Atla": "Skip Intro",
  "←→ değiştir · ↑↓ gez · ESC geri": "←→ change · ↑↓ move · ESC back",
  "Uyarı: tarayıcı kayda izin vermiyor, ilerleme kaydedilmeyecek.": "Warning: the browser blocks saving; progress won't be saved.",
  "◀ ÖNCEKİ": "◀ PREVIOUS",
  "SONRAKİ ▶": "NEXT ▶",
  "KONTROLLER": "CONTROLS",
  "GİZLİLİK": "STEALTH",
  "GANİMET": "LOOT",
  "Sola / sağa yürü": "Walk left / right",
  "Zıpla (el merdiveninde: tırman)": "Jump (on a ladder: climb)",
  "Çömel — sessiz yürür, saklanırsın": "Crouch — walk silently, hide",
  "Rafın / platformun üstünden aşağı in": "Drop down from a shelf / platform",
  "Koş (daha hızlı ama gürültülü)": "Run (faster but noisy)",
  "Eşyayı tut / çuvala at / bırak / kamyona yükle": "Pick up / bag / drop / load into truck",
  "Eşyayı çömelerek SESSİZCE yere koy": "Crouch to put an item down QUIETLY",
  "Eşyayı fırlat (dikkat dağıtmak için)": "Throw an item (distraction)",
  "Kasayı aç · kamyonla kaç": "Open safe / doors · escape by truck",
  "Kasayı aç · kapı aç · kamyonla kaç": "Open safe · open doors · escape by truck",
  "El fenerini aç / kapat (fareyle nişan al)": "Flashlight on / off (aim with the mouse)",
  "Harita (basılı tut)": "Map (hold)",
  "Duraklat": "Pause",
  "Karanlık ağ ekipmanları": "Dark web gadgets",
  "Her adım, düşen eşya, kırılan vazo SES çıkarır. Ses halkaları ne kadar gürültü yaptığını gösterir.": "Every step, dropped item and broken vase makes NOISE. Noise rings show how loud you are.",
  "Uyuyan ev sahibinin \"uyanma\" çubuğu seslerle dolar. Dolduğunda uyanır ve IŞIKLARI AÇAR.": "A sleeping owner's \"wake\" bar fills with noise. When it's full they wake up and TURN ON THE LIGHTS.",
  "Uyanık ev sahibi seni görürse şüphelenir; şüphe dolarsa KOVALAR ve POLİSİ ARAR.": "An awake owner who sees you grows suspicious; when suspicion fills they CHASE you and CALL THE POLICE.",
  "Dolap, perde, çalı arkasında hareketsiz dur; kanepe, yatak, sandık arkasında ÇÖMEL.": "Stand still behind wardrobes, curtains and bushes; CROUCH behind sofas, beds and chests.",
  "El feneri çok işe yarar ama uyanık birine yerini belli eder. Uyuyan birinin yüzüne tutma!": "The flashlight is useful but gives you away to anyone awake. Never shine it on a sleeping face!",
  "Polis çağrılınca süre azalır. Polis gelmeden kamyona ulaş!": "When the police are called your time drops. Reach the truck before they arrive!",
  "Bekçi köpeği seni görürse havlar; havlaması herkesi uyandırır. Isırırsa elindekini düşürürsün.": "A guard dog barks when it sees you, waking everyone. If it bites, you drop what you hold.",
  "Küçük eşyalar doğrudan ÇUVALA girer. Çuvaldaki eşyaya tıkla (G: sonuncusu) ve çıkar. Dolunca kamyona boşalt.": "Small items go straight into your SACK. Click an item in the sack to take it out (G: the last one). Empty it into the truck when full.",
  "Büyük eşyaları başının üstünde taşırsın. Ağır eşyalar seni yavaşlatır ve daha sesli yürütür.": "You carry big items over your head. Heavy items slow you down and make you louder.",
  "Sadece KAMYONA yüklenen ganimet sayılır! Kamyonun arkasında SPACE ile yükle.": "Only loot loaded into the TRUCK counts! Load it with SPACE at the back of the truck.",
  "Nadirlik: Sıradan · Nadir (mavi) · Epik (mor) · Efsanevi (altın). Parlayan eşyaları kaçırma.": "Rarity: Common · Rare (blue) · Epic (purple) · Legendary (gold). Don't miss glinting items.",
  "Her evde bir KASA var. Anahtarını bul, kasanın önünde E'ye bas ve şifre kadranını çöz.": "Every house has a SAFE. Find its key, press E in front of it and crack the combination dial.",
  "Vazo, cam, ayna, porselen KIRILIR. Kırılan eşya hem değer kaybı hem büyük gürültü demek.": "Vases, glass, mirrors and porcelain BREAK. A broken item means lost value and a loud crash.",
  "Kazandığın parayla dükkândan sessiz ayakkabı, büyük çuval, güçlü fener gibi geliştirmeler al.": "Spend your money in the shop on upgrades like quiet shoes, a bigger sack and a stronger flashlight.",
  "Kilitli kapıları maymuncukla aç; kamera ve lazerlerden kaçın ya da alarm panelini hackle.": "Pick locked doors; avoid cameras and lasers or hack the alarm panel.",
  "BÖLÜM SEÇ": "LEVEL SELECT",
  "TEKRAR OYNA": "PLAY AGAIN",
  "SONRAKİ BÖLÜM": "NEXT LEVEL",
  "KAMYON SENSİZ GİTTİ!": "THE TRUCK LEFT WITHOUT YOU!",
  "SOYGUN BAŞARILI!": "HEIST COMPLETE!",
  "HEDEF TUTTURULAMADI": "TARGET MISSED",
  "YENİ REKOR!": "NEW RECORD!",
  "KAMYONDAKİ GANİMET ({n} parça)": "LOOT IN THE TRUCK ({n} items)",
  "Kamyon bomboş... Reis hiç memnun olmayacak.": "The truck is empty... The Boss won't be happy.",
  "+{n} eşya daha": "+{n} more items",
  "İSTATİSTİKLER": "STATISTICS",
  "Geçen süre": "Time taken",
  "Evdeki toplam değer": "Total value in the house",
  "Kasa": "Safe",
  "AÇILDI ✓": "OPENED ✓",
  "Anahtar bulundu": "Key found",
  "Açılmadı": "Not opened",
  "Uyandırma sayısı": "Times woken",
  "Görülme": "Times spotted",
  "Kırılan eşya": "Items broken",
  "Yok ✓": "None ✓",
  "Geride kalan": "Left behind",
  " (çuvalda)": " (in sack)",
  "🔓 Yeni bölüm açıldı!": "🔓 New level unlocked!",
  "TEBRİKLER! Köprü altından yalıya taşındınız!": "CONGRATULATIONS! From under the bridge to a mansion!",
  "TEKRAR DENE": "TRY AGAIN",
  "Polis kapıya dayandı!": "The police showed up at the door!",
  "{n} seni suçüstü yakaladı!": "{n} caught you red-handed!",
  "Kamyondaki {v} de el konuldu...": "The {v} in the truck was confiscated too...",
  "Alarm sayısı": "Alarms",
  "Açılan kilit": "Locks picked",
  "Hedef": "Target",
  "{s} · Hedef {v}": "{s} · Target {v}",
  "HEDEF": "TARGET",
  "IŞINLANIYOR...": "TELEPORTING...",
  "SPACE: geç": "SPACE: skip",
  "REİS": "THE BOSS",
  "Reis ile konuş": "Talk to the Boss",
  "Kamyona bin": "Get in the truck",
  "Reis'in yanına git (A/D ile yürü)": "Walk over to the Boss (A/D to walk)",
  "Kamyonun kabinine git ve E'ye bas": "Go to the truck's cab and press E",
  "BÖLÜM {n} · BRİFİNG": "LEVEL {n} · BRIEFING",
  "Atlamak için ESC basılı tut": "Hold ESC to skip",
  "NAKLİYAT · 7/24": "MOVERS · 24/7",
  "> tor bağlantısı kuruluyor...": "> establishing tor connection...",
  "> şifreli kanal: AÇIK": "> encrypted channel: OPEN",
  "> hoş geldin, Red Crime. Bakiyeni kontrol et, soru sorma.": "> welcome, Red Crime. Check your balance, ask no questions.",
  "BAĞLANTIYI KES": "DISCONNECT",
  "> zaten sahipsin: {n}": "> already owned: {n}",
  "> satın alındı: {n} — kargo kamyonda": "> purchased: {n} — delivered to the truck",
  "> YETERSİZ BAKİYE. Önce biraz daha çal.": "> INSUFFICIENT FUNDS. Go steal some more.",
  "SAHİPSİN": "OWNED",
  "KALICI": "PERMANENT",
  "x{n} paket · elde: {c}": "pack of {n} · owned: {c}",
  "[ENTER] SATIN AL": "[ENTER] BUY",
  "// KARANLIK AĞ //": "// DARK WEB //",
  "anonim pazar · kripto ödeme · iade yok": "anonymous market · crypto payment · no refunds",
  "BAKİYE:": "BALANCE:",
  "Ekipmanlar soygunda 1-5 tuşlarıyla kullanılır. Kalıcı ekipmanlar otomatik çalışır.": "Use gadgets during heists with keys 1-5. Permanent gear works automatically.",
  "Altın Yüzük": "Gold Ring",
  "Pırlanta Yüzük": "Diamond Ring",
  "İnci Kolye": "Pearl Necklace",
  "Altın Kolye": "Gold Necklace",
  "Kol Saati": "Wristwatch",
  "İsviçre Saati": "Swiss Watch",
  "Küpe Seti": "Earring Set",
  "Altın Bilezik": "Gold Bracelet",
  "Külçe Altın": "Gold Bar",
  "Bozuk Para Kesesi": "Coin Pouch",
  "Madeni Para": "Coins",
  "Osmanlı Sikkesi": "Ottoman Coin",
  "Cüzdan": "Wallet",
  "Akıllı Telefon": "Smartphone",
  "Tuşlu Telefon": "Old Keypad Phone",
  "Kablosuz Kulaklık": "Wireless Earbuds",
  "Parfüm": "Perfume",
  "Makyaj Seti": "Makeup Kit",
  "Güneş Gözlüğü": "Sunglasses",
  "Dolma Kalem": "Fountain Pen",
  "Zippo Çakmak": "Zippo Lighter",
  "Madalya": "Medal",
  "Pul Koleksiyonu": "Stamp Collection",
  "Yakut": "Ruby",
  "Zümrüt": "Emerald",
  "Safir": "Sapphire",
  "Elmas": "Diamond",
  "Tomar Nakit": "Wad of Cash",
  "Dolar Destesi": "Stack of Dollars",
  "Euro Destesi": "Stack of Euros",
  "Puro Kutusu": "Cigar Box",
  "Retro Oyun Kartuşu": "Retro Game Cartridge",
  "Koleksiyon Figürü": "Collectible Figure",
  "Kehribar Tespih": "Amber Prayer Beads",
  "Nazar Boncuğu": "Evil Eye Bead",
  "Araba Anahtarı": "Car Key",
  "Dizüstü Bilgisayar": "Laptop",
  "Tablet": "Tablet",
  "Oyun Konsolu": "Game Console",
  "Oyun Kolu": "Gamepad",
  "Fotoğraf Makinesi": "Camera",
  "Drone": "Drone",
  "Bluetooth Hoparlör": "Bluetooth Speaker",
  "Nostaljik Radyo": "Vintage Radio",
  "Pikap": "Record Player",
  "Plak": "Vinyl Record",
  "Televizyon": "Television",
  "Monitör": "Monitor",
  "Oyun Bilgisayarı": "Gaming PC",
  "Mekanik Klavye": "Mechanical Keyboard",
  "Mikrodalga Fırın": "Microwave",
  "Tost Makinesi": "Toaster",
  "Espresso Makinesi": "Espresso Machine",
  "Blender": "Blender",
  "Saç Kurutma Makinesi": "Hair Dryer",
  "VR Gözlük": "VR Headset",
  "Projeksiyon": "Projector",
  "Seramik Vazo": "Ceramic Vase",
  "Çin Vazosu": "Ming Vase",
  "Büyük Yer Vazosu": "Large Floor Vase",
  "Saksı Çiçek": "Potted Plant",
  "Büyük Saksı": "Big Planter",
  "Kaktüs": "Cactus",
  "Orkide": "Orchid",
  "Bonsai": "Bonsai",
  "Mermer Büst": "Marble Bust",
  "Küçük Tablo": "Small Painting",
  "Yağlı Boya Tablo": "Oil Painting",
  "Ünlü Başyapıt": "Famous Masterpiece",
  "Duvar Saati": "Wall Clock",
  "Masa Saati": "Desk Clock",
  "Gümüş Şamdan": "Silver Candelabra",
  "Abajur": "Table Lamp",
  "Kupa": "Trophy",
  "Porselen Fincan": "Porcelain Cup",
  "Porselen Tabak": "Porcelain Plate",
  "İznik Çini Tabak": "Iznik Tile Plate",
  "Gümüş Tepsi": "Silver Tray",
  "Kristal Kadeh": "Crystal Glass",
  "Şarap Şişesi": "Bottle of Wine",
  "Yıllanmış Şarap": "Vintage Wine",
  "Viski": "Whisky",
  "Kitap": "Book",
  "Nadir El Yazması": "Rare Manuscript",
  "Ansiklopedi Seti": "Encyclopedia Set",
  "Rulo Halı": "Rolled Carpet",
  "El Dokuma Kilim": "Handwoven Kilim",
  "Gitar": "Guitar",
  "Keman": "Violin",
  "Saksafon": "Saxophone",
  "Trompet": "Trumpet",
  "Trampet": "Snare Drum",
  "Bağlama": "Bağlama (Saz)",
  "Darbuka": "Darbuka Drum",
  "Oyuncak Ayı": "Teddy Bear",
  "Uzaktan Kumandalı Araba": "RC Car",
  "Yapı Taşı Seti": "Building Brick Set",
  "Robot Oyuncak": "Toy Robot",
  "Antika Küre": "Antique Globe",
  "Teleskop": "Telescope",
  "Daktilo": "Typewriter",
  "Gramofon": "Gramophone",
  "Mücevher Kutusu": "Jewelry Box",
  "Müzik Kutusu": "Music Box",
  "Antika Ayna": "Antique Mirror",
  "Osmanlı Kılıcı": "Ottoman Sword",
  "Afrika Maskesi": "African Mask",
  "Fil Heykelciği": "Elephant Figurine",
  "Mısır Kedisi": "Egyptian Cat Statue",
  "Matruşka": "Matryoshka",
  "Akvaryum Kavanozu": "Fishbowl",
  "Kuş Kafesi": "Birdcage",
  "Fildişi Satranç": "Ivory Chess Set",
  "Çerçeveli Diploma": "Framed Diploma",
  "Nargile": "Hookah",
  "Av Borusu": "Hunting Horn",
  "İmzalı Forma": "Signed Jersey",
  "Altın Top Ödülü": "Golden Ball Award",
  "Şampiyonluk Kupası": "Championship Cup",
  "Modern Heykel": "Modern Sculpture",
  "Fabergé Yumurtası": "Fabergé Egg",
  "Antika İkona": "Antique Icon",
  "Akıllı Saat": "Smartwatch",
  "Krom Dambıl": "Chrome Dumbbell",
  "Havyar Kutusu": "Tin of Caviar",
  "Şifreli Sabit Disk": "Encrypted Hard Drive",
  "Bakır Tencere": "Copper Pot",
  "Döküm Tava": "Cast-Iron Pan",
  "Bıçak Seti": "Knife Set",
  "Porselen Demlik": "Porcelain Teapot",
  "Bakır Semaver": "Copper Samovar",
  "Bakır Cezve": "Copper Coffee Pot",
  "Lokum Kutusu": "Box of Turkish Delight",
  "Konserve": "Canned Food",
  "Reçel Kavanozu": "Jar of Jam",
  "Somun Ekmek": "Loaf of Bread",
  "Tulum Peyniri": "Wheel of Cheese",
  "İlk Yardım Çantası": "First Aid Kit",
  "Steteskop": "Stethoscope",
  "Mikroskop": "Microscope",
  "Şarjlı Matkap": "Cordless Drill",
  "Alet Çantası": "Toolbox",
  "Yarış Bisikleti": "Racing Bike",
  "Kaykay": "Skateboard",
  "Bovling Topu": "Bowling Ball",
  "Tenis Raketi": "Tennis Racket",
  "İmzalı Top": "Signed Football",
  "Meşe Şarap Fıçısı": "Oak Wine Barrel",
  "Bahçe Cücesi": "Garden Gnome",
  "Melek Heykeli": "Angel Statue",
  "Mangal": "Barbecue Grill",
  "Çim Biçme Makinesi": "Lawn Mower",
  "Bahçe Saksısı": "Garden Planter",
  "Bronz Heykelcik": "Bronze Statuette",
  "Deste Deste Nakit": "Bundles of Cash",
  "Kasa Altını": "Vault Gold",
  "Kasa Elması": "Vault Diamond",
  "Aile Yadigârı Kolye": "Family Heirloom Necklace",
  "Tapu Senedi": "Property Deed",
  "Kasa Anahtarı": "Safe Key",
  "Yatak": "Bed",
  "Çift Kişilik Yatak": "Double Bed",
  "Komodin": "Nightstand",
  "Gardırop": "Wardrobe",
  "Şifonyer": "Dresser",
  "Makyaj Masası": "Vanity",
  "Ranza": "Bunk Bed",
  "Oyuncak Sandığı": "Toy Chest",
  "Kanepe": "Sofa",
  "Berjer": "Armchair",
  "Sehpa": "Coffee Table",
  "TV Ünitesi": "TV Stand",
  "Kitaplık": "Bookcase",
  "Vitrin": "Display Cabinet",
  "Şömine": "Fireplace",
  "Piyano": "Piano",
  "Ayaklı Saat": "Grandfather Clock",
  "Dresuar": "Console Table",
  "Kaide": "Pedestal",
  "Çiçeklik": "Plant Stand",
  "Tezgâh": "Counter",
  "Üst Dolap": "Wall Cabinet",
  "Buzdolabı": "Fridge",
  "Ocak": "Stove",
  "Yemek Masası": "Dining Table",
  "Çamaşır Makinesi": "Washing Machine",
  "Küvet": "Bathtub",
  "Klozet": "Toilet",
  "Lavabo": "Sink",
  "Banyo Dolabı": "Bathroom Cabinet",
  "Çalışma Masası": "Desk",
  "Harita Masası": "Map Table",
  "Metal Raf": "Metal Shelf",
  "Şarap Rafı": "Wine Rack",
  "Koliler": "Boxes",
  "Sandık": "Chest",
  "Kombi": "Boiler",
  "Bilardo Masası": "Pool Table",
  "Bar Tezgâhı": "Bar Counter",
  "Bateri": "Drum Kit",
  "Duvar Rafı": "Wall Shelf",
  "Perde": "Curtain",
  "Çalı": "Bush",
  "Çit Çalısı": "Hedge",
  "Bank": "Bench",
  "Süs Havuzu": "Fountain",
  "Köpek Kulübesi": "Dog House",
  "KARABAŞ": "KARABAŞ",
  "Bahçe Masası": "Garden Table",
  "Çiçek Tarhı": "Flower Bed",
  "Bahçe Kulübesi": "Garden Shed",
  "Bahçe Lambası": "Garden Lamp",
  "◀ KAYDIR": "◀ SWIPE",
  "KAYDIR ▶": "SWIPE ▶",
  "▲ KAYDIR": "▲ SWIPE",
  "▼ KAYDIR": "▼ SWIPE",
  "UZUN KAYDIR": "LONG SWIPE",
  "DOKUN": "TAP",
  "BASILI TUT": "HOLD",
  "▼ + DOKUN": "▼ + TAP",
  "HARİTA": "MAP",
  "Dokun: geç": "Tap: skip",
  "Atlamak için ▶ düğmesini basılı tut": "Hold the ▶ button to skip",
  "Her ses kapıdan duyulur · X: vazgeç": "Every sound carries through the door · X: cancel",
  "Ekrana basılı tut: del · Baskıyı yeşil bantta tut": "Hold the screen: drill · Keep the pressure in the green band",
  "3 hatada alarm çalar · Kaydır: ok · X: vazgeç": "3 mistakes trigger the alarm · Swipe: arrow · X: cancel",
  "Devam etmek için dokun": "Tap to continue",
  "Başlamak için dokun": "Tap to start",
  "Parmağını ekranda sola ya da sağa kaydır ve tut: yürürsün.": "Swipe left or right on the screen and hold: you walk.",
  "Aynı yöne daha uzun kaydır: koşarsın. Hızlıdır ama ÇOK gürültü yapar!": "Swipe further in the same direction: you run. Fast, but VERY noisy!",
  "Parmağını yukarı fırlat: zıplarsın. Mobilyaların üstüne böyle çıkarsın.": "Flick your finger up: you jump. That's how you get on top of furniture.",
  "Aşağı ve yana kaydırıp tut: çömelerek yürürsün. Neredeyse hiç ses çıkmaz.": "Swipe down and sideways and hold: you sneak crouched. Almost silent.",
  "Ekrana basılı tut: el fenerini kapat, sonra tekrar aç.": "Hold the screen: turn the flashlight off, then on again.",
  "Eve gir ve bir eşyanın yanında ekrana dokun. Küçük eşyalar çuvala girer.": "Go inside and tap the screen next to an item. Small items go in the sack.",
  "Ganimeti kamyonun arkasına götür ve dokunarak yükle. Sadece kamyondakiler sayılır.": "Carry the loot to the back of the truck and tap to load it. Only what's in the truck counts.",
  "Kapalı bir kapının önünde ekrana dokunarak aç. Kilitliyse maymuncukla açarsın.": "Tap in front of a closed door to open it. If it's locked, you pick the lock.",
  "ganimeti kamyona yükle ve süre bitmeden kamyonun yanında dokunarak kaç.": "load the loot into the truck and tap next to the truck to escape before time runs out.",
  "Öğreticiyi atla ▸": "Skip tutorial ▸",
  "Kaydırıp tut: yürü": "Swipe and hold: walk",
  "Zıpla (el merdiveninde tut: tırman)": "Jump (hold on a ladder: climb)",
  "Al / çuvala at / bırak / yükle / aç / kaç": "Grab / bag / drop / load / open / escape",
  "Çömel, ikinci parmakla dokun: SESSİZCE koy": "Crouch, tap with a second finger: put down QUIETLY",
  "Eşya elindeyken: fırlat": "While holding an item: throw",
  "Elin boşken: el fenerini aç / kapat": "Empty-handed: flashlight on / off",
  "Mini haritaya basılı tut: büyük harita": "Hold the minimap: big map",
  "Duraklat (sağ üstteki düğme)": "Pause (top-right button)",
  "Sadece KAMYONA yüklenen ganimet sayılır! Kamyonun arkasında SPACE ile yükle (dokunmatik: dokun).": "Only loot loaded into the TRUCK counts! Load it at the back of the truck with SPACE (touch: tap).",
  "ÇIKIŞ": "QUIT",
  "Çuvaldan çıkarıldı: {n}": "Taken out of the sack: {n}",
  "Kilitli: önce {n}. bölümü bitir.": "Locked: finish level {n} first.",
  "MAĞAZA": "STORE",
  "Reklamsız oyun": "No ads",
  "Her soygunda +60 saniye": "+60 seconds every heist",
  "Çuvalda +10 yuva": "+10 sack slots",
  "Her gün {v} hediye": "{v} gift every day",
  "GERİ YÜKLE": "RESTORE",
  "Mağaza yalnızca Android / iOS uygulamasında açık.": "The store is only available in the Android / iOS app.",
  "Ödeme ekranı açılıyor...": "Opening payment...",
  "{m} hesabına eklendi!": "{m} added to your account!",
  "Premium zaten açık.": "Premium is already active.",
  "Premium açıldı! Reklamlar kaldırıldı.": "Premium unlocked! Ads removed.",
  "Premium açıldı! Günlük hediye: {m}": "Premium unlocked! Daily gift: {m}",
  "Satın alma iptal edildi.": "Purchase cancelled.",
  "Satın alma tamamlanamadı. Tekrar dene.": "Purchase failed. Please try again.",
  "Satın alımlar kontrol ediliyor...": "Checking purchases...",
  "Premium geri yüklendi!": "Premium restored!",
  "Geri yüklenecek satın alım bulunamadı.": "No purchases to restore.",
  "SATIN AL · {p}": "BUY · {p}",
  "Tek seferlik ödeme": "One-time payment",
  "oyun parası": "game money",
  "EN İYİ TEKLİF": "BEST VALUE",
  "Ekipman parası ya da premium: soygunu kolaylaştır.": "Gear money or premium: make the heist easier.",
  "Premium günlük hediye: +{m}": "Premium daily gift: +{m}",
  "2X PARA · REKLAM İZLE": "2X MONEY · WATCH AD",
  "2X PARA!": "2X MONEY!",
  "EMİN MİSİN?": "ARE YOU SURE?",
  "RIZAMI GERİ ÇEK": "WITHDRAW CONSENT",
  "KABUL ETMİYORUM": "I DECLINE",
  "KABUL EDİYORUM": "I ACCEPT",
  "Kabul etmek için metni sonuna kadar kaydır ▼": "Scroll to the end to accept ▼",
  "Oyunu oynamak için onay gerekli": "Consent required to play",
  "Gizlilik Politikası ve KVKK metnini kabul etmeden Red Crime oynanamaz. Metni tekrar okuyabilir ya da uygulamayı kapatabilirsin. Soruların için bize e-posta gönder.": "Red Crime can't be played without accepting the Privacy Policy. You can read it again or close the app. Email us with any questions.",
  "GİZLİLİK / KVKK": "PRIVACY",
  "Ödeme onay bekliyor. Tamamlanınca oyunu yeniden aç.": "Payment is pending. Reopen the game once it completes.",
  "Alarm panelini hackle": "Hack the alarm panel",
  "Kapıyı aç": "Open the door",
  "Kapıyı kapat": "Close the door",
  "Kilitli kapı: kilidi kır": "Locked door: break the lock",
  "Diziyi aşağıdaki oklara dokunarak gir": "Enter the sequence by tapping the arrows below",
  "3 hatada alarm çalar · X: vazgeç": "3 mistakes trigger the alarm · X: cancel",
  "Parmağınla pimin altından yukarı sürükle: yeşil çizgide oturur": "Drag up from under a pin with your finger: it sets on the green line",
  "KASA  · DOKUN": "SAFE  · TAP",
  "Kaçmak için tekrar dokun! (Kamyondaki ganimetle)": "Tap again to escape! (with the loot in the truck)",
  "Eşya elindeyken ekrana basılı tut: fırlatırsın. Ev sahibini başka yere yönlendirir.": "Hold the screen while carrying an item to throw it. It lures the owner somewhere else.",
  "Aynı yöne uzun kaydırırsan koşarsın ama koşmak çok ses çıkarır.": "Swipe further in the same direction to run, but running is very loud.",
  "Ekrana basılı tutarak el fenerini açıp kapatabilirsin; kapalı fener seni daha zor fark ettirir.": "Hold the screen to toggle the flashlight; with it off you are harder to spot.",
  "Mini haritaya basılı tutarak evin haritasını açabilirsin.": "Hold the minimap to open the house map.",
  "Kapalı bir kapıya dokunarak aç. Kilitliyse maymuncukla açarsın.": "Tap a closed door to open it. If it's locked, you pick the lock.",
  "Saklan: perde ya da dolap önünde hareketsiz dur, kanepe ya da yatak arkasında aşağı kaydırıp çömel.": "Hide: stand still in front of a curtain or wardrobe, or swipe down to crouch behind a sofa or bed.",
  "Geç: dokun": "Skip: tap",
  "[DOKUN] SATIN AL": "[TAP] BUY",
  "Ekipmanlar soygunda alttaki yeşil düğmelere dokunarak kullanılır. Kalıcı ekipmanlar otomatik çalışır.": "Use gear during a heist by tapping the green buttons at the bottom. Permanent gear works automatically.",
  "Koda dokun: kopyala · Başka yere dokun: ana menü": "Tap the code: copy · Tap elsewhere: main menu",
  "Küçük eşyalar doğrudan ÇUVALA girer. Çuvaldaki eşyaya dokunarak çıkar. Dolunca kamyona boşalt.": "Small items go straight into the BAG. Tap an item in the bag to take it out. Empty it into the truck when full.",
  "Sadece KAMYONA yüklenen ganimet sayılır! Kamyonun arkasında ekrana dokunarak yükle.": "Only loot loaded into the TRUCK counts! Tap the screen at the back of the truck to load it.",
  "Her evde bir KASA var. Anahtarını bul, kasaya dokun ve şifre kadranını çöz.": "Every house has a SAFE. Find its key, tap the safe and crack the combination dial.",
  "Kapıya / kasaya dokun: aç": "Tap a door / safe: open",
  "Bahçede Kont var: eğitimli bir Doberman. Kokunu alır, izini sürer; çalıya saklanman onu kandırmaz.": "Kont guards the garden: a trained Doberman. He picks up your scent and tracks it; hiding in a bush won't fool him.",
  "Fırlattığın bir şeye bir kez kanar, ikincisinde kanmaz. Eve girersen kapının önünde bekler. Bir de iki bekçi, onlarca kamera ve şehrin en iyi alarm sistemi.": "He'll fall for a thrown object once, never twice. Go inside and he'll wait at the door. Plus two guards, dozens of cameras and the best alarm system in town.",
  "Köpek": "The dog",
  "{n} bu numaraya ikinci kez kanmadı!": "{n} won't fall for that twice!",
  "{n} izini sürüyor!": "{n} is on your scent!",
  "{n} seni saklandığın yerde buldu!": "{n} sniffed you out of your hiding spot!",
  "{n} kapının önüne oturdu, çıkmanı bekliyor...": "{n} sat down by the door, waiting for you to come out...",
  "{n} izini sürüyor": "{n} is tracking you",
  "{n} kapıyı bekliyor": "{n} is guarding the door",
  "Sertleştirilmiş çelik pim! Kesik kesik del.": "Hardened steel pin! Drill in short bursts.",
  "Pime geldin: baskıyı azalt.": "You hit a pin: ease off the pressure.",
  "Pimler kesildi! Tornavidayı sok ve silindiri çevir.": "Pins sheared! Insert the screwdriver and turn the cylinder.",
  "Tornavida kaydı! Biraz geri çevir, parçayı düşür.": "The screwdriver slipped! Turn back a little to drop the fragment.",
  "Parça düştü. Şimdi çevir!": "The fragment dropped. Now turn!",
  "Takıldı: kırık bir pim parçası var.": "Stuck: a broken pin fragment is jamming it.",
  "Kam döndü, kapı açıldı!": "The cam turned, the door is open!",
  "2/2 · TORNAVİDA": "2/2 · SCREWDRIVER",
  "KESİT": "CROSS-SECTION",
  "kesme çizgisi": "shear line",
  "Pim {a}/{b}": "Pin {a}/{b}",
  "Pimde baskıyı azalt · Mavi pim: kesik kesik del": "Ease off at a pin · Blue pin: drill in bursts",
  "KİLİT DİLİ": "LATCH BOLT",
  "Basılı tutup kilidin çevresinde saat yönünde döndür (ya da D)": "Hold and circle the lock clockwise (or D)",
  "Parmağını kilidin çevresinde saat yönünde döndür": "Circle your finger clockwise around the lock",
  "Takılırsa zorlama: biraz geri çevir, sonra ileri": "If it jams, don't force it: turn back a little, then forward",
  "Anahtar döndü. Şimdi şifre kadranı.": "The key turned. Now the combination dial.",
  "Şifre tamam! Kolu çeviriyorsun...": "Combination set! Turning the handle...",
  "{i}. disk oturdu!": "Wheel {i} is set!",
  "Kadran boşa döndü. Tık sesinin en güçlü olduğu yerde dön.": "The dial spun free. Reverse where the click is loudest.",
  "DİSKLER": "WHEELS",
  "SAĞA çevir (saat yönü)": "Turn RIGHT (clockwise)",
  "SAĞ": "R",
  "SOL": "L",
  "SOLA çevir (saat yönünün tersi)": "Turn LEFT (counter-clockwise)",
  "STETOSKOP": "STETHOSCOPE",
  "KULAK (stetoskop yok)": "EAR (no stethoscope)",
  "Kadranı fareyle tutup çevir ya da A / D (SHIFT: hızlı)": "Grab and turn the dial with the mouse, or A / D (SHIFT: fast)",
  "Kadranı parmağınla tutup çevir": "Hold the dial with your finger and turn it",
  "Tık en güçlüyken dur ve ters yöne dön: disk oturur": "Stop where the click is strongest and reverse: the wheel sets",
  "Yanlış dönüş ses çıkarır · ESC: vazgeç": "A wrong reversal makes noise · ESC: give up",
  "Yanlış dönüş ses çıkarır · X: vazgeç": "A wrong reversal makes noise · X: give up",
  "Dış kapıyı delerken pime gelince baskıyı azalt; mavi (sertleştirilmiş) pimleri kesik kesik del.": "When drilling the front door, ease off at each pin; drill the blue (hardened) pins in short bursts.",
  "Kasa kadranında tık sesi en güçlüyken dur ve ters yöne dön.": "On a safe dial, stop where the click is loudest and reverse direction.",
  "Zeki köpekler kokunu takip eder; izin yarım dakikada kaybolur.": "Clever dogs follow your scent; your trail fades in about half a minute."
});
})(window.RC);
